var level1 = "-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b--" +
	"r-b-u,j-r-b-u,v--r---r-k,r-r-k,r-r,j--r---u,j---r,j---r--b-u-n,r-n,u,v--" +
	"r--r-r--r--r,j---u,v-k,u-r,tp3-k,u-r-b-u,j-b-u-r,rs-b-b-u-b-b-u,rs,v-r,j-n,b-n,b-n,b-n,r--" +
	"r-b-u,j-u,v-b,v-u-b-u-b,v-u,j--r-r-b,v-u,j--r,j--r,-r,---b-b-b-u,v-b-b-b-u-n,r--" +
	"r--b-b-b-b-r---r-b-u-r-b-u,j-b-u--r,rs-u--r,--r,---r,-n-n,b-n,b-n,r--" +
	"r-r---r,j-u-u,j--p-r,j-b-b--b,v-b-b,v-b-b-b,v-b-b,v-r--r,j---r-n,r,j--r-n,r--" +
	"r-u,j---r,-u,j,v-u,v-b-b,v-u-u,j,v-i,u,v-r,--r--r--r--r-r-b-u-b-b,v-u-n,r-b-u,j-n,r--" +
	"r-u,j-b-b-u-u,j-b----u,j-u-r-b-u-b-u-b-u-b-u--b-b-b--r-n,b,bs-n,b-n,b-n,u--" +
	"r-d,r-d,r,j-d,r-n-n-n,u,v-b--u,j-b-u-b--b-b-b-b-b,v-b-b,v-r-n-n-n,r--b-b-b--u--" +
	"r-d,u,j-d,u-d,u,v-n,b-n,u,j-b,v-r-r--b-b-u,v-u,j-r,j--r--r--r-u-n,u,v-n,r-n,r-r-b,v-r-k,r-r-k,r--" +
	"r--r-b-b,v-b-u-u,j-u,j-u-r,j-b--u,v-r-b-u-b-u-b-u-d,b-d,u-n,r-n,u,j-u-r-r-k,r-r-k,r--" +
	"r-b,v-u,j--u-r-b,v-u-b,v-u--r-r-r--b-u,j-b-b,v-b-b-b-b-b,v-b-i,u-u,v-r-k,u-r-k,r--" +
	"r---r,j-r-u,j-b-b-b,v-r,rs-b-u-u,v-u,rs-r--r,j-n,b-n,b,v-n,u,j-n-n,b-n,b-n,b,bs-n,b-n,r-r-r-r-r-k,u--" +
	"r-b-b-u,v-r--r--r-r--b--b-r-b,v-u-r-r-r-n,r-k-k,r-r-k,r-n,r,j-r-r-r,j--r--" +
	"r---u-r-b,v-u-b-u-r-r,j-r-u-r-r-b-u-r,j-r,j-r-n,r-k,b-k,u-u,bs-k,u-n,r-u,bs-r-u,v-b-ds,u--" +
	"r-b-u--r-b-b,v-b-b,v-u-r--r-u,rs-b-b-u,v-r-r-u-n,b-n,b-n,b,v-n,b-n,b,v-n,u--b-r--r--" +
	"r--r--u,v,j-b-u-b-b-u-u,v-b-u---p-r-u-r--r,j-b-b-u,v-r-r,j-r-k,u-r-b-u,v--" +
	"r-b-u,j-u-b,v-b-b-b-b-b-b,v-b-b-b-b-b--r-u,v-b-u-b,v-b-u,j-r-u,v-b--u,rs-u,rs-u,v--" +
	"r-h,st,b-h-h,st,r-b-b-u-h,st,r,j--r--r-b,v-b-u,j-r--b-b-r,j-r-r--b-b-r-u,j-r,j-u--r--" +
	"r-r-h,st,b-h,st,b-h,st,b-h,st,b-h,st-h,st,r-b-u-b-u,v-r-st-st,r-r-r-b,v-u,v,j-u-r-u-r--r-r---r-b-u--" +
	"r-b-b,v-b-r,j-r-h,st,b-h,st,r-u,j-b,v-b,v-r-r-st,b-st,u,j-u-r-r-r--b-r-u-b,v-b,r-r--b-b--r--" +
	"r,rs-b-u-r-r-u-r-h,st,b-h,st,r-u-st,r-r-u,j-b-b-u,j-r-u,bs-u-r-r,j-u----u,j-u--r,j-b-u,v--" +
	"r-b,v-u-u,j-r-r-b,v-u-h,st,b-h,st-st,r-b-b-b-b,v-b-b-b,bs--r-r,b--b-sp-u,j-b-r-b-u,v--r--" +
	"r-b-b-b,v-r,j-u-b-r-r-h,st,b-h,st-h,st-h,st,r-b-b-u--r--i,b-n-n,r--u,v--tp2,u,j-u--r,j-b-u--" +
	"r-ds-r-u-b,v-r-r-r,j-b-u-st,b,v-h,st,b-h-h-h,r-ds,n,u,j-b-u,v-r-k,u-n-n-n,u,v-r-u--r,j-b-u-h-h,u--" +
	"r-b-b-u,v-u-u,j-u-b-u,j--b-r-h,b-h,b-h,b-h,b-h,r-u-r-u,j-n,b-n,r-b-u-r,j-b-u-h-h-h,u-r--" +
	"r-n-n,b-n-n,b-n,r-r,j-b-u-r,j-r-n-n,b-n,b-n-n,r-h,b-h,b-h-h,b-h,r-b-b-b-u-h-h,b-h,b-h,u--r--" +
	"r-n,r-u,j-n,r,j-u-n,r-r-u,j--r-u-n,r,j-b-u-n,b-n,u,v,j-b-u-r-k,u-h-h-h-h-h-h,r---r,j-b-u--" +
	"r-n-n,b-n,p-n,b-n,r-b,v-b,v-b-r,j-r-n,r,j--r-r,j-r,j-b-u-r-b--h-h-h-h-h,r-b,v-b-u-b-u,bs--" +
	"r-n,r-u,j-n,r,j-u-n,r-r-r-r,j-u,v-u,v-n,r-b-u-u-u,v,j-r-k,r-tp1,r-k,r-b-b-h,b-h-h,b-h,u-b-b,v-b--r--" +
	"r-n,b-n,b-n,b-n,b-n,u-u-u-u-b-u-n,u,j-b-u-b-u-u-k,u-u-k,b-k,b-k,b-k,u-h,u-k,b-k,u-b-b-u-b-u-";
var level2 = "-b-b-b,bs-b-b-b-b-b-b,v-b-b-b,v-b-b-b-b-b-b,v-b-b-b-b-b-b-b-b-b-b-b-b,bs--" +
	"r---r--r---r-n-n-n,r-d,u,j--r--r--r-st,r,j--r-r,j--r-r,j-n-n,r-r,j--r--" +
	"r-b,-b,v-u-b,v-u-b-b-u,v,j-n,b-n-n,r,j-b-b,v-u-b,v-u,j-b-r-st,u-b-u,v-u-b-u,v-u-n,b-n,u,v-u-b-u,v--" +
	"r,j-b-b,v-b-b,v-u,j-n,r-n,b-n-n,r-n,b-n,u,v-r-b--u,v--r,j-u-r,j-r-b-b-b-b-b-b---b-u,j--" +
	"r---r--r-n-n,r,j-n,b-n,u,v--r--r-u---u,v--r--r-r,j-n-n-n,b-n,u,j-b,v-r,j--r--" +
	"r-b-b-u-b-u-n,b-n,b-n,u,v---u,j-b-u,v-n,r,j-b-u-r-b,v-u-ds,b-u,v-r-n,b-n,u,bs--c1,r-r-r-b-u,v--" +
	"r--r---r-n,b,v-n-n,r-b-u,j-n,r-r-n,b-n-n,r--r--r--r-u,j-r---p,u-r-r-b-u--" +
	"r-b,v-u-b,v--u,v-r-n-n,r,j-n-n-n,r--r-n,b-n,u,v-b-u,j-b-u,j-b-u,v-r-r,j-b,v-p,u--r-r,j--r--" +
	"r-b-b-u-r-p,u-u,j-n,b-n,r-n,b-n,b-n,u,v-b,v-p,u--r--r-r--r,j-p,r-u,j-b-b-u,v-b-u,v-r-b-u,v--" +
	"r--b-b--b-b-r-n,u,j-n-n-n,u-b-b-b-u,j-b-u-tp3,r--r-r--r-k,u-n,b-n,b-n,u-r-b-u--" +
	"r-r,j--r-r--r-r-k,r-n-n,r-b,v--r-n-n,r--r-r-b-u-r-b-u,v--r--r-u,j--r--" +
	"r-r-b-u-r-b-u,j-r-k,r-n,b-n,b-n,u--u,j-n-n,r--r,rs--b-b-b-b-u,v,j-b-u-b,v-b-u,v-b-u,v--" +
	"r-r,j--r-r--r-r-k-k-k-k,r-n,r-utp,u,v-n,b-n,u,v-b-u,v-r-k,b-k,b-k,b-k,u--r-p-r--r-b-u--" +
	"r,j-r-b-u-r--r,j-r-k-k-k-k,r-b-u--r--r-r-h-h-h-h-b-u-b,v-u-b-u,v-b,bs-u,j--" +
	"r-u,j--r-r-b-u-r-k-k,b-k,b-k,b-k,b-k,r--r--r-r-h-h-h-h,r-sl,b-sl,r,j--r,j-r-b-b-us,u,v--" +
	"r-k,r--r-r--r,j-u-k,r--b-b-r-k,r-b,v-u-c2,b,v-u-r-h-h-h-h-h,r-sl,u--r-b-u,j--r--" +
	"r-k,r-b-u-r-p,b-u-k-k,r-r-c1-u,v-r-k,r-n-n-n,r-k,u-r-h,b-h,b-h,b-h-h-h,r-b-b-b-u,v-p,b-u--" +
	"r-k-k-k,r-r-k-k-k-k,r-r-r-tp2,u-r-k,r-n,b-n,b-n,u-r,j-r-n-n-n,r-h-h-h-h-h-h-h-h-h,r--" +
	"r-k-k-k,r-r-k-k-k-k,r-r-b-b-u-k,u---p,r-r-r-n-n-n,u-h,b-h-h-h,b-h,b-h,b-h,b,v-h,b-h,u--" +
	"r-k-k-k,r-i,u,v-k,b-k,b-k,b-k,u-b-b-b-u,j-r,j-b-b-u-u,v-tp1,r-p,n,b-n,u,j-r-k,u-h,b-h,u---r-n-n-n,r--" +
	"r-k-k-k,r-r-b,v-b-b-b-b-b-b-b--b-b-b-b-u--r,rs-r---r-p--r-n-n-n,r--" +
	"r-k-k-k,r--r--b-b,v-r-b-b-r-u,j-n-n,r--r-i,r,j-b-u-r---r-b-b,v-u-n,b-n,b-n,u,v--" +
	"r-k-k-k,r-b,v-u-u-b-r-r--b-p,r-r-n,b-n,u-b-u,j-r--p,r-r-b-b-u,j---r---r--" +
	"r-k,b-k,b-k,r-r---r-r-r-r-r-u,v-r-b,v-u,rs--r-r,j-b-p,u-r---r---r---r--" +
	"r-us-r-k,u-r---r-r-r-r-b-u-r-b-us,u,bs-b-u,j-r--r-dtp,r---r,j-b-b-r-b,v-p,b-u--" +
	"r-b-b-u,v-r-b-b,v-u--u-b-b--u-b-r--r-r,j-b-u-dtp,u-b-b-u--r-st,r---r--" +
	"r---r-r-b--r-b,v-b-b---b-u,v-r-p,b-u,j-r--r-st-st,r-st-st,r--r-st,r---r--" +
	"r-b,v-b-u-r,j-ds,u-b-u,v--b-b----b-r-sl-sl,r-r,j-b-u-st,b,v-st,u-st,b,v-p,st,u-b-u,v-st,r,j-b-b-u--" +
	"r-b,v-b-b--b-b-u-r--b-r-r-r--u-sl,b-sl,u,j--b-b,v-b-b,v-b-b,v-i,u,rs-st,b-st,b,v-st,r--r--" +
	"r---r-r---r-r-u-r-r-u,bs-r-u-r--r-r--r-st-st,r-st-st,r---r-st,r--r--" +
	"r,rs-b-b-u,bs-u,j-b-b-u-b-b-u-u-d,u-b-b-u-b-u,j-u,v-b-u-st,b-st,u-st,b-st,u-b-b-u-st,u,j-b,-u,bs,rs-";
var level3 = "-b-b-b-b-b-b,v-b-b-b-b-b-b-b-b,v-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b--" +
	"r-k,u-h-h-h,u-r--r,rs--r--r-k-k,u-u,bs-k,u-sl,b-sl,u,j--r,j-i,u,bs,j--r,rs--r--r-sl,b-sl,b-sl,u,v-k,u--" +
	"r-h-h-h,u-b,v-u,j-b-u,j-p,b-u,v,j--u-k,r-r--r-r,rs-b-b-u-i,r-b-u,j-b-u,j-b-u--r,j--r--" +
	"r-h-h,u--b-r--u,j--r-r-k-k,u-r-b-u,bs--r--r,j-r,j-n-n,r,j--r,j--r,j-b-u-b-u,bs--" +
	"r-h,r-r-r-ds,u,j-r,j-u-r,j-b-u-r-k,r-b-u,j-b-b-b-u,rs-b-u-r-n,b-n,u,rs-b-p,u-b-u--r,j--r--" +
	"r-h,r-r,j-b-b-u-b-u---u-k,r-n-n,r-b,v-b-b-b-b-dtp,b-us-dtp,b-b-b-b-b-u,j-b-u-b-u,bs--" +
	"r-h,r--r--tp3,r,j--b-b-u-k-k,u-n,b,v-n,u,j------r-r--r---r,j-p,n-n,u,v-r--r--" +
	"r-h,r,j-b-u,j--r,rs-u-k-k,b-k,b-k,u---r,j-b-b,v-b-b-u,v-u-r--r,j--rtp-r-n,u-b-u,j-p,b-u,bs--" +
	"r-h-h-h,r-b-u-k-k,u-r--r,j-b-b-u-r,rs-p,b---u-r,j-u-b,v-u-b-b,v-u--u,v-r--r,--" +
	"r-h,b-h,b-h,b-h,u-k-k,u-b,v-u,j-b-u---r--r-b-u,bs--r--r,j--r-p,n-n,r-u,v-b-u,v,j--u--" +
	"r-k,b-k,b-k,b-k,b-k,u--b-r--u,j-b-b,bs-u,v-b,v-u-b-u,rs-b-u-b-u-b-u,j-n-n,r,j--u,v-n,r-u-k,r--" +
	"r-b,bs-u--r-r-r-tp2,u,j-r,j-u-k,r-sp,b--r-st-st,r,j-n-n,r,j--r,j--r,j-tp3-r,j-n,b-n,u-r,b-n,b-n,u-k-k,u--" +
	"r--r,j-b-u-r,j-b-b-u-k-k-k,r-b,-u,bs-st,b,v-st,u-n,b-n,u-b-u,rs-b-u,v,rs-b-u-k-k,b-k,b-k,b-k,b-k,u-r--" +
	"r-b,bs-u--r--r-k-k,b-k,b-k,b-k-k,r-u,bs,rs-u-b-b-tp4,u,bs-u,bs-u,bs-b-b,v--u-k,r-r,j-b-b-b-b,v-u--" +
	"r-b-u,v-b,v-u,j-b,bs-u-k,r--r-r-k,b-k,r-sp,u,bs,rs-b-b,bs-u,rs-sp,u,bs,rs-u,bs,rs-u--r-u-k-k,u-r-b,v-n,b-b-u,j-r--" +
	"r--u-r--i,r-k-k,u-b,bs-u,j--r-k,u-r--sp-r-r-rtp,u,rs-u,bs-b-u-k-k,u--r--n---r--" +
	"r-p,u,bs-b-u-b-u-k,r-n-n-n,u-b-utp,u-u-r,rs-sp-sp-sp,r,rs-r-u,bs,rs-u-k-k,b-k,u-p-b-u--n-b-b-u,v--" +
	"r--r,j--u-k-k,u-n,b-n,u,rs---u-k,r-u,bs-b,bs-sp,b,bs-u-u,bs-u,bs-k-k,u--b-u--r--n,u-b,bs-b-u--" +
	"r-b-u,v-u-k-k,u--b-u,rs--r-k-k,u-sp,u,bs,rs-b-b-u,rs-sp,u,rs-u-k,r--u-n-n,r,j-b-u-u-b-b--u--" +
	"r,j--u-k-k,u--u-r-n,r,j-b-u,v-k,r-u,rs-u-k-k,b-k,b-k,b-k,b-k,u-r,j-n,b-n-n,r,rs-b-b-r--r,j-u-r,j--" +
	"r-u-k-k,u--u-b,v-u,j-n,u-n,b-n,r-k,b-k,b-k,b-k,u-n,r,j-st-st,r--r,rs-b-r-n,b-n,u,j--r-r,j-p-u--u--" +
	"r-k,b-k,u--u--b-r--u,j-n-n,r,j--r-n-n,r-st,b-u,j-b-b,v-r-r--u-b-tp3,u-r-u--u-k,r--" +
	"r-b,v-b-u,v-r-r-tp2,u,j-r,j-u,bs-n,b,v-n,u-n,u,bs-b-u,j-n,b-n,b-n,b-n,b,v-n,b-n,u-u-r-u,j-b--r---u-k-k,u--" +
	"r-r--r-r,j-b-b-u-u--c2,r-b-b-b-b-b-b-u-b,bs-u-u,bs-u,v--r,j-b-u--u-k-k,u-r--" +
	"r-r-b,v-u--r---u,v-b,bs-r,j-n,b-n,b-tp1,n,b-n,b-n,b-n,b-n,b-n,b-n,b-n,b-n,r--u,v---u-k-k,u--u,v--" +
	"r-u,v--u,j-b-u-b,v-u-r-r-u---u,j-b---u--u,j-r-n,u-u--b,v-u-k-k,u-n,r-u-u,j--" +
	"r-b-u,bs--r---r-b-b,v-u-b-u,j-r-r,rs-b-u-b,bs-u-b,bs-u---r-r-k-k,u-n,b,v-n,u,j-b-u--" +
	"r--r--r-us--r--r--r-b-r----b-tp1,b-b-b-b-b-u,j-u-k,r--b-r--u,j--" +
	"r-b,bs-u-b,bs-u,j-b-b-r--u,v--u--u--p-u-k-k,b-k,b-k,b-k,b-k,b-k,b-k,b-k,u-r-i,u,j-r,j-u-r--" +
	"r-b--r--b-r-u,v-u-b-u-b-u,bs--b,bs-u-k-k,u--r,j---u,v--r-r,j-b-b-u--u--" +
	"r-k,u-b-u,rs-u-b-b,v-b-b-u,j-b-b-b-u-ds,u,v-k,b-k,u-b-b-u-b-u-b-b-u,j-b-u,j-b-b-u-k,u-";
var level4 = "-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b--" +
	"r--b-b-b-b-b-b-b-b-b-b--b-b-b-b-b-b-b-b-b-b-b-b-b-b--b-b-r--" +
	"r-r-r---u,j-b-b-u,j-b--rtp,r-r-k,r---sp---u-i,r-n,b-n-n-n,sp-n-n,r-r-k,b-k,u-r--" +
	"r-r-r-b,v-u,j--r-n,b-n-n,r--r-r-k,r---sp--r,j-u,j-r,j-u,j-n-n-n,sp-n-n,r-r--r-r--" +
	"r-r,j-b-u-us,u,rs-b-b-u,j-n,b-n,u,j-b-u-r-k,r-b-b-sp,b-b-b-u-r-n,b-n,b-n,b-n,sp,b-n,b-n,u-r-tp4,b,v-u-r--" +
	"r-r--r--r--r-n-n,r--r-r-k,r-b,v-b-b-b-utp,b-b-ds-b-utp,b-b-b-b-u,j-r-h-h,r-r--" +
	"r-r,j-b-u,j-b-u,j-b-u,j-n,p,b-n,u,j-b,-u,v-r-k,r-u-r--r--r-r--r--r-h,r-u,rs,bs-r-h,b-h,u,v-r--" +
	"r-r,j--r,j-sl-sl,r,j--r,j--tp2,r,j--r-r-k,r--r-b,v-tp3,u,j-b-r-r-tp1-u,j-b-u,v-h-h,r-r--r-r--" +
	"r-r-b-u-sl,b-sl,u-b-u-b-u,rs-b-u-r-k,u-b,bs-u,j-u,rs-b-u,j-u,j-u-u-b-b-u,j-h,b-h,u-r-b,v-u-r--" +
	"r--b-b-b-b-b-b-b-b-b-b-i-b,bs-b,bs-b,bs-b,bs-b,bs-b,bs-b,bs-b,bs--b-b-b-b-b--b-b-r--" +
	"r-r-tp2-n,u--r--r-b--u-tp2,r-r--r-sl-sl,r-st-st,r--r-r,j--r-r--r,j-r-k-k,r-r--" +
	"r-r-n--r--u---b-b-r-r-tp3-u-sl,b-sl,r-st-st,u-b-r-r-b-u,j-u,j-b-u-r-k,b-k,u-r--" +
	"r-r-n,u--b--b--b---u-r-u-r-r-sl,u-p,st,u-sl,r-r-u--b-b-b-b-b--b-b-r--" +
	"r-r--r--b-r--b-u--u-r--r-st-st,r-sl-sl,r--r-r-h,n-h,n,r,j-r,j--r-r-k-k,r-r--" +
	"r-r-r-b-r-d-d,b-d,r-d--r-r-r-b,v-u,v-st,b,v-st,u,v-sl,b,v-sl,u,v-b,v-u,v-r,j-h,n,b-p,n,u-u-b-u,j-r-k,b-k,u-r--" +
	"r-r-b---d,b-d-d-d-u--u--b-n,b-n,b-n,b-b- b-b-b-sp-b,v-b,v-b,v-b,v-b,v-b,v-b,v-b,v-r--" +
	"r-r-r-r-r-d-d-d,r-d,b-n-n,r-r-r-k-k,r-n,r,j-c3-r-r-h-h,r,j-r--r-sl-sl,r--r-n-n,r-r--" +
	"r-r--b-b-d-d,u-d-d,b-n,r--r-r-k,b-k,u-r-b-u,j-u,j-h,b-h,u-r-b-r-sl-sl,u-b-r-n-n,u-r--" +
	"r-r-b--b---r--n,b--r--b-b--b-b-b-b-b-r-r-p,u-sl,u-st,n,r-p,r-u-n,u-r-r--" +
	"r-r-n,r--b-r-r-b-r--r-u-r-k-k,r-r-n-n,r,j-rtp,r,j--r-r--r-st,n-st,n,r--r--r-r--" +
	"r-r-n,b-tp2,u-b-u-b-b-b-u-b-tp2,u-r-k,b-k,u-r,j-n,b-n,u,rs-u,rs-b-u,j-r-b,bs-u,bs-st,n,b,bs-st,n,u,bs-b,bs-u,bs-b,bs-u,bs-r--" +
	"r--n,b-n,b-n,b-n,b-p,n,b-n,b-p,n,b-rtp,b-b-u--b-b,v--b-b-b-b-b-b-b-b-b-b-b-b-b-b-r--" +
	"r-r-k-k,b-k,b-k,b-k,b-k,b-k,b-k,b-k,b-k,r-r-h-h,r-r-k-k,b-k,b-k,b-k,b-k,b-k,b-k,b-k,b-k,b-k,b-k,b-k,b-k,r-r--" +
	"r-r-k,r-b,v-r,rs-b-u,rs--u,j-r,rs-p,u-k,r-r-h,b,v-h,u-r-k,r-b-r,j-b-r,j-b-r,j-b-r,j-b,v-r,j-b,v-r-k,r-r--" +
	"r-rtp,r-k,r-r-b-u,j-b-u-h,r-b,v-r-k,r-r-n-n,r-r-k,b-k,r-u,bs-r-u,rs,bs-r-u,bs-r-u,rs-r-u-n,r-u-k,r-tp1,r--" +
	"r-u-k,r-b,v-r,rs-b-b-u,rs-h,u,rs-r-u-k,r-r-n,b-n,u,v-r,j-tp1,u-k,r-b-u-b-u-b-u-b-u,rs-n,b-n,u,v-r-k,r-r--" +
	"r-k-k,u-r-u--u-n-n,u,rs-b-r-k,r-p,r--sp,r-r-k-k,u--u-r-n,b-n,u,v-r,j-b-r,rs-r-b-u,v-k,b-k,r--" +
	"r-k,r--u,rs-b-u-n,b-p,u-k,u-r-u,v-k,r-u-b-u-u-k,r-r,rs-u,j-b-u,rs-p,n,b-n,r,j-b-u,j-u,v-b,v-u,j-b-r-k,r--" +
	"r-k,r-u,v-h-h,u,j--u,j-b-r-b-r-k,b-k,b-k,b-k,b-k,b-k,u-b-u,bs,j-n,r-r,rs-r-n,u,v,j-r-k,u-r-b-r-r-u-k,r--" +
	"r-k,r-h,b-h,u,j-b-u,rs-n,b-p,n,u,rs-b-u,j-u,rs-u,rs-u,rs-u,rs-i,u,bs,rs-u,rs-u,rs-u,rs-n,b-n,u-u-b-u-b-u,j-b-u-u,j-b-u-k,r--" +
	"r-k,b-k,b-k,b-k,b-k,b-k,b-k,b-k,b-k,b-k,b-k,b-k,b-k,b-us,u-k,b-k,b-k,b-k,b-k,b-k,b-k,b-k,b-k,b-k,b-k,b-k,b-k,b-k,b-k,b-k,u-";
var level5 = "-b-b-b-b,v-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b--" +
	"r-b,bs-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b,bs-rtp,u-r--r,j--r--r,j--r,j-r--" +
	"r-b-b-b,v-b-b-b-b-b-b,bs-b-b-b-b-b-b-b-b-b-b-i,u,j-r,j-b-u-b-u,j-b-u-b-u-u,v--" +
	"r-k-k,r-r---r---r,j-r---r,j-c1-ds,r--p,r,j---r-r--r,j--r--r,j--r-r--" +
	"r-k,b-k,u-r,rs---r,j---r-r--sp-r--r--r---u-r,j-b-u-b-u,j-b-u-b-u,j-u--" +
	"r-h-h,r-r-b-b-u-b-b-u-r,j-b-b-u-b-u,j-b-u-b-u,v-us-r-k,b-k,b-k,b-k,b-k,b-k,b-k,b-k,b-k,u--" +
	"r-h,b-h,u,j,bs-r---r,j--r-k,r-r,j---r-n-n,r,j--r--r-b-r--r--r--r---c3,r--" +
	"r-r-u-r,j-b-b-u-b-u,v-k,r-r--sp-p,r-n-n,r--r---r-r--r--r--r,j---r--" +
	"r--r,j-r,j---r--r-k,r-r-b-b-u,j-n,b-n,u-b-u,j-b-b-u-r-b-u,v-b-u,v-b-u,v-b-b,v-u--" +
	"r--u-r--p-r--r-k,r-r--u-sl,r--r--r---r,j-r,j-b-b,v-b-b,v-b-b,v-b-b,v-u--" +
	"r-u,v-r-r-b-b-u,j-b-u-k,r-r-u,v,j-sl,b-sl,u,j--r--r,j-b-b-u-r--r--r--r---r--" +
	"r--r-r---r,j--r-k,r-r,j---r-b-u,j-b-p,u---r,j-u--r--r--r,j---r--" +
	"r-b-r-r,j--p-r--r-k,r-r---r----r,j--tp4-r-r,rs-b-u-b-u-b-u-b-b-u--" +
	"r-r-u,v-r-b-b-u-b-u,v-k,r-u-b-b-u,j-b-b-b-u-b-b,v-u-r---b,v--tp1--b,v--r--" +
	"r--r----r--r-k,r---r--r--r-st-st,r--r-r--u-r-b--u-r-b-r--" +
	"r--u,-b,v---r,j-b-u-k,r---r,rs-p-r--r,rs-st-st,r--r-r-r,j-b-sp-u,j-r,j-b--u,j-r--" +
	"r-u,v-r-r-b-b-u-k-k-k,r-b-b,v-u-b-u,v-b-u,v-st,b-st,u,v-b-u,v-r--r-u,v---r-u,v--r--" +
	"r--r-r-k,b-k,b-k,b-k,b-k,b-k,r-i,b-b-b,v-b-b,v-b-b,v-b-b,v-b-u,v,j-r,j---b,v--tp3--b,v--r--" +
	"r-b-r-r---r,j--r-k,r---r--r-sl-sl,r-sl-sl,r-sl-sl,r-r--u-r-b--u-st,r-b-r--" +
	"r-r-u,v-r,j-b-b-u-b-u,v-k,r---r,rs--r-sl-sl,r,rs-sl-sl,r-sl-sl,r-r-r,j-b-rtp-u,j-r,j-st,b-st,tp2-st,u,j-r--" +
	"r--r-r,j---r-n-n,r-k,r-b-b-u-b-u-sl,b-sl,u-sl,b-sl,u-sl,b-sl,u,j-r,j--r-u,v---r-st,u,v--r--" +
	"r--u-r--p-r-n-n,r-k,r-st-st,r,rs-b-b----b-b--r-r-b-b-b-b-tp1,b-b-b-b-u--" +
	"r-u,v-r-r-b-b-u,j-n,b-n,u-k,r-st,b,v-st,u--r-b--u--r--r-r---r,j--b-b-r-d-d,r--" +
	"r--r-r---r,j--r-k,r--r---u,j-r,j-b--r-b-u-u,v-b-b-r-r,j-i-i,r,j-r-d,r-d,u--" +
	"r-b-u,j-r--p-r--r-k,r--r-b-u---r-b-u,rs--r---r-u,v-r-i,b-i,u-r-d-d,r--" +
	"r-h-h,r,j-r,j-b-b-u-b-u,v-k,r-b,v-u-h-h,r-b--u-h-h,r--r--rtp-r,rs-u,v-p,b-b,v-b,v-u-d,u-d,r--" +
	"r-h,b-h,u-r,j---r--r-k,r--r-h-h-h,u,j-r,j-h,b-h-h,r-b,v-u--b-u-r-r--r-r-d-d,r--" +
	"r--p,r,rs-r-b-b-u,j-b-u-k,r-b-u,v-h,b-h,u---r-h,b-h,u-n-n,r-r---r-r-ds-r-r-d,r-d,u--" +
	"r-rtp-r-r-k,b-k,b-k,b-k,b-k,b-k,u--r--r-b--u--r-n-n,r-r-b-b-u-u,v--r-u,v-d,b-d,u,v--" +
	"r--r-r--r,j-b-b--r,rs--r---u,j-r,j-b--r-n-n,r,j-r----b-b-b-b--r--" +
	"r-b-u-u,rs-b-b-b-u-b-u-b-u,v-b-u-b-b-u-b-u-n,b-n,u-u-b-b-u,rs-b-b-b-u-b-u-";
var level6 = "-b-b-b-b-b-b-b-b-b-b-b,v-b-b-b-b-b-b-b-b,v-b-b-b-b,bs-b-b-b-b-b,v-b-b--" +
	"r--r,j--r,rs--r,j-p-r,j--b,v-b,v-b-u-u,j--r,j-c2,u,v-k,r--r--r-r--r--r,j-n-n,r-r,j--" +
	"r,j-b-u-b-u-b-u,rs-b-u-b-u,rs-b-b-r,j-r-b-r-r-k,r-b,v-u-b,bs-u-u,bs-b-u,v,j-b-u-n,b-n,u-r--" +
	"r---r--r---u,j-i,u,j-b--r-r-u-us,r-u-r-k,r--r--r-r-d-d,r--r--r-r--" +
	"r---u,j-b,v-u-b,v-u---r-b-u,v--b-b,v-b-u-k,r-b,v-u-b-u,j-u,v,j-d,b,v-d,u-rtp,b-u,v,j-rtp,b-u-r--" +
	"r-b-u,j-n-n,r-u,v-------r-r-r-r-sl,n-sl,n,r-k,r--r--r,j-r,j--r--r--r-r--" +
	"r--u-n,b-n,u,j-u,v,j-b-b-b-b-b-b-b-u-u,v-r-sl,n,b-sl,n,r-k,r-b-i,u,v-b-u,v-u,bs-b-u-b-u,j-b,v-sp,u-r--" +
	"r-r-d-d,b,v-d,r,j-d,n-d,n,b,v-d,n,r,j-d-d,b,v-d,r,j-d-d,b,v-d,r-b-b,v-u,j-sl,n,u-k,r--r,j--r-r--r--r--r,j-u--" +
	"r-s,u,bs-d,r-u-d,r-d,n,r-u-d,n,r-d,r-tp4,u-d,r-d,r-c3,u-d,r--r,j-st-st,r-k,r-b-u,v-b-u,j-sp,u,v,j-b-u,j-b,v-rtp,u-b-u,rs-s,r--" +
	"r-d,u-d,b-d,b-d,u-d,n,b-d,n,b-d,n,u-d,b-d,b-d,u-d,b-d,b-d,u,j-b,v-u-st,b-st,u-k,r--r--r,j-r,j--r--r--r-s,r--" +
	"r-p-b-b-b-b-b-b-b--b-b-b-r--r--r-k,u-b-u,j-b-u,bs-u-b-u-c1,b-u-b-u,j-s,u,v--" +
	"r-r-c3,u,j--r,j--r,rs-r,j-tp3,u-i,r--i-r-dtp,u-b-p,u,v,j-b,v-u-sp-ua-sp,r-b,v-b-b-b-b-b-b-b-b-u,v--" +
	"r-r-u,j-b-u-b-u--r-i,r--ra-r-----r-la-sp-ra,r--r--r--r--r--r--" +
	"r-b,v-b-b,bs-b-b-r-b,v-u-i,r-n-n-n,r-b,v-b--b-u,v-la-sp-ra,r-b,v-u-b-u,v,j-tp1,b-u,j-b,v-u-b-u,v--" +
	"r-ext-r,j--r,j-u-r--r-i,r-n-n-n,r-tp2,b-tp2,r-r--u---r--r--r--r--r--r--" +
	"r--r--r,j-u-r-p,b,v-u-i,r--p--r-tp2,u-u,v-u---p-r-b,v-u-b-u,v-b-u,v,j-b-c3,u-b-u,v--" +
	"r-b-u-b-u,j-u-r-n-n,r-i,r,rs-b-rtp--r--ra-r----u--r--r--r--r--r--" +
	"r,j--b-b--b-u-n,b,v-n,u-i,r-k,r---r-b,v-b,v-u,v---r-k,r-b-u,v-b,v-u-b-u,v-b-u,bs,rs-b-u,v,j--" +
	"r-rtp,r--r-r----r-i,r-k,r--------sp-la,r-k,r--r,rs-h-s,r-d-d,r--r-st,n-st,n,r--" +
	"r-u-b,v-u,v,j-u,j--b--r-i,r-k,r-b----p---ra-sp,u-k,r-b-u-h,b,v-h,u-d,b-d,u,v-b-u,bs-st,n,b-st,n,u,v--" +
	"r--r-st,n-st,n,r-r-st,u,v--r-i,r-k-k,r-----rtp-la-r-k-k,r-h-h,r-h-h,r-d-d,r--r,rs--r--" +
	"r-b-u-st,n,b-st,n,u----r-i,r-k-k,r--ext-----r-k-k,r-h,b,v-h,u,j-h,b,v-s,u-d,b-d,u,v-b-u-b-u,v--" +
	"r--b-b,bs-b-b-b-b-u-il,r-k-k,r-b-b----b-u-k-k,r-rtp,n-n,r--r-d-d,r,j--r--r--" +
	"r-r-dg-dg-dg,r--b-b-b-r-k-k-k-k,r-n-n-n,r-k-k-k-k,r-n,b,v-n,u-b,v-u-d,b,v-d,u-b-u,v-b-u,v--" +
	"r-r-dg,b-dg,b-dg,u,v-r-sl-sl,r-r-r-k-k-k-k,r-n-n,da-n,r-k-k-k-k,r-st-st,r,j--r,j-st-st,r-sl-sl,r,j-n-n,r--" +
	"r-r-b-b-u-r-sl,b-sl,u,j-r-r-k-k-k-k,r---r-k-k-k-k,r-p,st,b,v-st,u-b-u-st,b-st,u-sl,b-sl,u-n,b-n,u,v--" +
	"r-b-b--b-b-b-b-u,v-u,v-k,b-k,b-k-k,r-ra-ua-la,r-k-k-k,b-k,u-b-b-b-b-b-b,v-b-b-b-u--" +
	"r-k-k,r-r-k-k,r-st-st,r--r--r-k-k,r---r-k-k,r-d-d,r,j-p-p,r-r-n-n,r-us-r,j--r,j-rtp,r--" +
	"r-k-k,r-r-k-k,r-st,b-st,u,v-b-u,v,j-b,v-u-k-k,r---r-k-k,r-d,b-d,u-p,b-p,u,j-u,v,j-n,b-n,u,rs-b-u-b-u-r--" +
	"r-k-k,r-r-k-k,r--r,j--r,j--r-k-k,r-dtp-dtp-dtp,r-k-k,r-tp1-r,j--r,j-r,j-n-n,r-ext-ext,r--r-r--" +
	"r-k,b-k,u-u,bs-k,b-k,u-b-u-b-u-b-u-k,b-k,u-dtp,b-dtp,b-dtp,u-k,b-k,u-b,v-u-b-u-u-n,b-n,u,j-ext,b-ext,u,j-b-u,j-u,v-";
var level7 = "-b-b-b-b-b-b-b-b,v-b-b-b,v-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b--" +
	"r-st-st-st,r-h,b-h,r,rs-st,r-st-st-st,r,j-st-st,r-st,r,j-st,r---r--r,j---r---r,j---r-gt-gt-gt,r--" +
	"r-st-st-st,r,j-r-h,u-st,u,j-st,b-st,b-st,u-st,b-st,u,rs-st,u-r---r-b-u---r,j---r--p-r,j-gt-gt-gt,r--" +
	"r-st,b-st,b,v-st,u-b-b-r-s-h,r-st-st,r,j--b-u--b-b-r-r,j-b-b-u-b-b,v-u-b-b-u-gt,b-gt,b-gt,u--" +
	"r-b,v-b-r,j-st,b-st,u,v-r-h-h,u-st,b-st,u-r-r--u-r-r-r,rs-b-b-r-b-u,v-r-b,v-u--b--b-r--" +
	"r--r-b-r,j-d,st,sp,r-r-h,u,v,j-h,n,r-h-h,r,rs-r-u,j-r,j-b-u,v,j-r-r--r,j-b--b,v-b-b-u,j-r-tp4,u,j-r-d,u,j-r--" +
	"r--p-r,j-r-d,st,u-r-h,n,b-h,n,u,j-h,b-h,u-r-h,r-r-h,r-r-u-r-b-b,v-u-r-b-b-r,j-r-b-b-b-b-u--" +
	"r-b,v-b-u--b-b,v-u,j--b--u-h,u,v-r,rs-h,u--b-b,bs-u,j--b-b-b-r-r-b-u-ds,r-u,j-r-r--" +
	"r---u,v-r---r-r-k,u-r-h-h,r-b-r-r-h-h-h,r-r-k,b-k,b-k,u-r--b-b-b,v-b-u-u,v--" +
	"r-b,v-u-b-u-b-b-u-b-i-u,bs-h,b-h,b,bs-h,u-r-u,v-h,b,v-h,b-h,u,v-b-b--b-u,v-r-n-n-n,r-d-d-d,r--" +
	"r-r--r,j--r---i,b-i,u-r,j-b-b-b-b-u,v-h,b-h-h-h,r-r,j-r-r-b-r-n,b-n-n,u-d,b-d-d,u--" +
	"r-u,v-b-u,v-ext,b-u,j-b-u-k-k,u-b-b-b-b-b-b,v-r-h,b-h,b-h,u-r-r,j--r-r-n-n-n,r-d-d-d,r--" +
	"r--r-r-n,b,v-n,b-n-n,r-k,r--b-b,v--b-b-u-b-b-b-b-u,v-r-b-u,j-u,j-n,b-n,b,v-n,u-d,b-d,b-d,u,bs--" +
	"r-p,b-u,j-u-d-d,r-rtp,n,b-n,u,v-k,u-r--r-r--b-b-b-b-r--r--b-b-b-b-u,bs-s,b-h-h-h,r--" +
	"r-b,bs-b-u-d,b,v-d,u---u-r-b,v-u-r-r--b-b-r-r-b,v-u-r-s-s-h,r-h-h-h,r,j-h,b-h,b,v-h,u--" +
	"r--r--u-b,v-b-u,j-r-r--r-bl,r-r-r-rtp,b-r-r-r--r-r-s-h-h,r,j-h-h-h,u,j-h,r,j-h-h,r--" +
	"r-b-u,v-r---r,j--r-r-b-u,v-r-r-b-tp3,u-r-r-bl,r-b-u,v-r-h,b-h,b,v-h,u,v-h,b,v-h,u,v-h-h,r-h-h,r--" +
	"r-b,v-b,v-r-b,v-b-u-b-u-r--r-r-b-b-b-u-r-r--r-r-h-h-h,r-h,st,r-h-h-h,u,v-h,b,v-h,r--" +
	"r-r-c1,r-r-b-b-b-b-b-r-b,v-u-b-b-b-b-b-u-r-b,v-u-r-h,b-h,b,v-h,u,j-h,st,sp,r,j-s,b-h,u-h,n-h,n,r-h,u--" +
	"r-r,j-sp,r,j-b-u,j-r-gt-gt-gt,r-r--b-b-b-r-b,v-b-b-b-b-b-u-h,b-h-h,r-h,st,u,v-h-h,r,j-h,n-h,n-h,n,r--" +
	"r-u,v-u,v-r,j--r,j-gt,b-gt-gt,r,j-r-r-st-st-st,u-b-b-b-b-b,v-b-r-h-h,r,j-h,b-h,u,v-h-h-h,r-h,n,b-h,n,b,v-h,n,u--" +
	"r-r-n,r-r---r-gt,b,v-gt,u-r,j-u-st,b-st,r-k,b-k,b-k,b-k,b-k,u-d,b-d,u,j-u-h,b-h,b-h,b-h,b,bs-h-h-h,u,j-h-h-h,r--" +
	"r-r,j-n,r,j-u-b,v-b-u--b-b,v-b-r-st,r-----r-b-r,j-b-b,v-u,j--u-h,b-h,u-s,b-h,b-h,b-h,u--" +
	"r-u-n,u,v,j-b-sp,b,v-dtp,u,j-b-u,j-b-sp,b,v-u,j-u,j-st,u--p-da--r-c2,r-u,j-st-st,r-r,j-u,v-b,v--r-sp-d-d-d,r--" +
	"r-rtp,r-b-b,v-u---b-b-b-b-b-r--ra-rtp-la-r-r-r,j-st,b-st,u-r--r-b-u,v-d,b-d,b-d,sp,b,v-d,u--" +
	"r--b,v-b-b-b,v-r--b--b-r-r---ua--r-r-b--b-u,v--r-p---r,j--r--" +
	"r-r--r,j--r-r-r,j-d,u-r,j-tp1,u-r,j-r-b-b-b-b-u-r-r-r-k,u-tp2,u-b-u-b,v-b-p,b-u-b,v-r--" +
	"r-r-b-u-b-u-r-b-b-b-b-u-r-k,r-utp-utp-utp,r-k,r-r,rs-r,j--u-n-n-n,r-b-r-b,v-sp,b-u-u,v--" +
	"r-r--r,j--r---b-b-b-b-r-k,r-utp-utp-utp,r-k,r-r-r-r-n,b,v-n,b-n-n,r,j-r,j--r-b-u,j-r--" +
	"r-r-b,v-u-b-u,v-p-r--r,j--r-r-k,u---r-k,u-r-u-b-b-u-ext,n,b-n,u-r-b-u,j-r--r--" +
	"r-b-b-b-b-b-b-u-b,v-u-b-u,v-b-b-b-b-b-b-b-b-b-bl,b-bl,b-b-b-b-b-b-u,j-b-u-";
var level8 = "-b-b-b-b-b-b-b-b-b-b-b-b-b,bs-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b--" +
	"r--r,rs-n-n,r,rs-b----r--bl,r,j---r,rs-la,b-u,v,j-b-bl,b-bl,b-bl,b-bl,b-bl,b-bl,b-u,j--b-b-b--u,j--" +
	"r--r-n-n,r-rtp,u,j--sp--r--r-b-b-u,bs-sp-r---r,j-u-u,j---r-r---r-sp,r,j-r--" +
	"r-b,bs-u-n,b-n,u-b-b-b-b-u,bs-b,v-u,bs--r-r--r-b,v-b-u,rs--r,rs-b-b-u,v-b-b,v-b,v-b,v-u-u,v--" +
	"r---r,j-u-sp,u,j---r-r-u---r,j-r-b-u,bs--r----r--r-s-r-r--r-st,r--" +
	"r-b,v-b-u,rs--r,rs-b-bl,b-u,v-r-u,v-da,b,bs--r-r--p,r--r-b-b,v-b-u--r--r-r--r-st,r--" +
	"r-n-n,r-sp---r-n-n,r-r,rs--sp,r-b-u-u,bs-b,v-u-b-u,rs-b-b,bs-b-u,rs-b-u-sp,b-u-r-b-u-st,u--" +
	"r-n-n,r-b-b,v-b-u-n-n,r-r--r---r-b,v-b-bl,b-bl,b-bl,b-bl,b-bl,b-bl,b-bl,b-bl,b-bl,b-b-us-b-b-u,j--" +
	"r-n,b-n,u,rs-b-b-b-u,rs-n,b-n,u,rs-u-b-u,j-b-b-u--r--r,j--p,r,j-p-r,j-gt-gt,r,j-tp3-r-r-r,j--r--" +
	"r-k-k,b-k,b-k,b-k,b-k,b-k,b-k-k,r-n,b-n-n,r--r-ra-r--r--r--r-gt-gt,r--r-bl,r-u-b-u,v--" +
	"r-k,r-st-st,r,j-rtp,u,j-dg-dg,r-u,v-k-k-k,r-n,b-n,u,j-b-u,rs-b-u,rs-b-u-b-u,rs-sp,b-u-gt,b-gt,u,bs-b-u-bl,r-n,r,rs--r--" +
	"r-k,r-st,b,v-st,u-u,v-dg,b-dg,u,v-u,v-k,b-k,b-k,b-k,b-k,b-k-k,b-k,b-k,b-k,b-k,u--r,rs-b-b-bl,b,v-u,rs--r-bl,r-n,r-b,v-u--" +
	"r-k,r-b,v-u,j-sp,u,v,j-b-bl,u,v-sp,u,v---u,v,j-b-r-k,r-c1-c1-c1-c1-c1,r,j--r----r-s-r-bl,r-n,r--r--" +
	"r-k,r--r-r--r,rs-u,v-b-u,bs,j-r-sl,u,v-r-k,r-c1-c1-c1-c1-c1,r-b,v-u-b---u-b-u,v-bl,r-n,u,v-b,v-u--" +
	"r-k,r-b,bs-u,j-u,j-b-u-u,v--r--r,j-r-k,r-c1-c1-c1-c1-c1,r---r,rs-b-u,rs--sp-r-bl,r-r--r--" +
	"r-k,r-b,bs-u,j-b-b-u,j-b-b-u-b-u,bs-r-k,r-c1,b-c1,b-c1,b-c1,b-c1,u-bl,b,bs-b-u,j-u-tp2,u,j-b-b-bl,u-bl,r-r-rtp,b,v-u,bs--" +
	"r-k,r--r--r-r,j-b-r--u,j-r-r-k-k,b-k,b-k,b-k,b-k,u-n,b-n,b-i,n,b-n-sp,n-n--r-bl,r-r--r--" +
	"r-k,r-b-u,j--u,rs-b-u-u,rs-u-b-u-r-k,r---r,j-u-u,j-n-n-n,r-n-n-n--r-bl,r-u,bs-b,v-u--" +
	"r-k,r-b-u,v-u,v,j--r---u,v,j--r-r-k,r-b,v-b-u,rs--r,rs-n,b-n,b-sp,n,u,v,rs-n-n-n--r-r---r--" +
	"r-k,r--r,j-b-b-u-b-u,j-p,b-b-u,j-r-k,r--bl,r----r-n-n,r-n-rtp,n-n--u,j-u,j-b-b-p,u--" +
	"r-k,r-b,bs-u-b-b,v-b-b-b-b-b,bs-b-u-k,r--r-b-b,v-b-u-n-n,r-n-n-n-i,n,r--sp,r,j---r--" +
	"r-k,r-b-u,v-b-r-k-k,b-k,b-k,u-u,v-k,b-k,b-k,u-b-u,rs-b-b-b-u,rs-n,b-n,u-n-n-n-n,r--r-b-b-u,bs--" +
	"r-k,r-b,bs-u,v-r-r-k,r-d-d-d-d,sp-d-d,r,j--b-b-b-b-b-b-b-u,j-n,b-n,b-n,b-n,u,bs-b,v-u,bs--r-r--" +
	"r-k,r-r-ds,r-b,v-u-k,r-d-d,r-d-ds,r-d-d,sp,r-r--la,r,j-n-n-n,r,rs-bl--r,j--r--r-u---r-r--" +
	"r-k,r-u,j-u,rs-b-u-k,r-d-d,r-d-d,r-d-d,r-r--r-n,b-n,b-n,u,bs-b,bs-b-utp,u--sp,r,rs-b,v-r-u,v-b,bs--r-r--" +
	"r-k,b-k,b-k,b-k,b-k,b-k,u-d,b-d,b-d,b-d,b-d,b-d,u-r-b,v-u,bs--r-r-r--r-b,bs-u,v-r,j-u,v--r-b-u-u,bs--" +
	"r-d,n-d,n-d,n-d,n,r,j---r,j-u-u,j---r-r-u---r-r-r,j---r-u--r--r-h,n-h,n-h,n,r--" +
	"r-d,n-h-h-d,n,r-b-b-u,rs--r,rs-b-ua,b-u-r-u,v-bl,b,bs--r,j-r-r---u,bs-u,v-b,bs-u-b-u,j-h,n,b-h,n,b,bs-h,n,u--" +
	"r-d,n-h-h-d,n,r--r----r--r-r--r-b-u-u,bs-sp,u,bs-b-u--r--i-r-h-h,r-h-h,r--" +
	"r-d,n-h-h-d,n,r--r-b-tp1,b,v-b-u--r-r--r---r---r--r---r,rs-h-h,r,rs-h-h,r--" +
	"r-d,n,b-d,n,b-d,n,b-d,n,u-b-u,rs-b-b-sp,b-u,rs-b-u,rs-u,rs-b-u,j-b-b-u,rs-b-b-u,j-b-u-b-b-u-h,b-s,u-ext,b,v-h,u-";
var level9 = "-b-b-b-b-b-b,v-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b,bs-b-b,v-b-b-b-b,v-b-b--" +
	"r,j-b-r--r,j--u-k-k,u---r,j--r-h,b-h-h,r-b--p--r--r,j--r--r---u,j--" +
	"r-k,u-u,j-b-u-u-k,b-k,u-b-b,v-b,bs-u-b-b-u,v-h,b-h,b-h,u-b-b-b-u,j-b-u-b,v-u,j-b-u,v-b-u-k,u--" +
	"r-r-k,b-k,b-k,b-k,r--r,j--r--r,j--i,u-h-s-h-s-h,r---r--r,j-r,j-u,v-u,v-u,v-k,b-k,r-r--" +
	"r-u,v,j-b--r-k,u-b-u-b,v-u-b,v-u-r-h-h-h-h-h-h,r-b--r,j-b-p,u,j-r,j-u,j-u,rs-u,v-r-k,r-r--" +
	"r--r-b-u,v-u-k,r--r,j----u-h,b-h-s-h-h,b-h,b-h,r-b-b-u-p,u,j-r,j-u,v,j-u,v,rs-u-u-k,u-r,j--" +
	"r--r---r-k,r-b,v-u-b-b-r-h-h,r,j-h,b,v-h-h,r-b-r,j-h-h,r-ds,st,b-st,u,j-u,bs,j-r,j-u,j-u,v,j-u-k,u-b,v-u--" +
	"r-b-u-b,v-b-u-k,r--p-ext,b,v-r,j-u-h-h,u-r-h-h,r,j-r,j-u-h,b,v-h,u-p,b-u,j-u,j-r,j-u,v,j-u-k,r---r--" +
	"r---u-k-k,b-k,u--p,r,j-tp2,u,v,j-p,r-h-h,r-s,b-u,v-h,b-h,u,v-r-h-h,r,j-i-i,r--p,r,j-r,j-u,v-k-k,r-b-b-r--" +
	"r-b-u-k-k,u--r-ext-sp-ext-p,u-h-h,u--r-h-h,r-u-h,b,v-h,u-b,v-u,j--p,r,j-r,j-u,v-k,b-k-k,b-k,u-u,j--" +
	"r-k,b-k,b-k,u-r,j-b,v-u,rs-b-p,b-u-s-h,u,j-b,v-b-u-h-h-h-h,r---r-b-u,j-u,v,j-u,j-u,v-k,u-r,j-r-k,u--" +
	"r,j-b-u,j--i,r--b-u-h-h,b-h,u,v--r-p-r,j-h,b-h-h,sp-h,r-b-b-u,v-k-k,r-u-r,j-u-b-u,v--u,j--" +
	"r-h-h,r-b-u,j-u-h-h,b-h,u-r-b-b-u-b,v-u,j-r-h-h-h,u-r-b,v-u-k-k-k,r--r,j-b-u-u-h,r--" +
	"r-h,b,v-h,b-h,b-h-h,r,j-h,u-dtp,r-b--b-u-r--r-r-h-h,r-b,v-b-u-k-k-k-k,r-b-b-u-r-h-h,r--" +
	"r-b-b-u,v-h-h,u-u,rs-bl,r,rs-u,rs-r-u-b,v-u,v,j-b-u-r-h,b,v-h,u-d-d-d,r-k,b-k,b-k,b-k,b-k,r---u-h-s,r--" +
	"r-h,b-h,b-h,b-h,u,j-b-b-da-b-bl-b-u-sl,r,rs-b-u,v-i,r-h-h,r-d,b-d,b-d,r,j--r--r-k,u-b-u-h-h-h,u--" +
	"r---b,v-u-r-u,rs-bl,r,rs-sp,u,bs,rs-bl,r,rs-sp,u,bs-sl,b-sl-sl,u-r-r-h-h-h-h,r-d,u--r--b-u-h-h-h,b-h,u-r--" +
	"r--u-r-b--b,bs-bl-b,bs--b,bs-u-sl,u,v-b-u,v-r-h,b-h-h-s-h,r-b-u,j-u-h-h-h,b-s,u-b-ds,u,v-r--" +
	"r,j-r-s,b--u-r,rs-u,rs-bl,r,rs-sp,u,bs,rs-bl,r,rs-sp,u-b-b-u,r,j-d,u,v,j-r-r-h,b-h,b-h-h,r-h-h,rtp-h-h,b-h,u--r,j--r-r,j--" +
	"r--r-u,v-b--b-sp-bl,b,bs-bl-b-u-ext,r-b-r-tp1,r,rs-r--r-h,b-h,u,j-h,b-h,b-h,u-b,v-u,j-b,v-u--r-r--" +
	"r--b-b-u-u-u-r-u-r-k,u-ext,b--u,j-u,v-u-u,v,j-b-u-h,b,v-h,u,j-b-b,v-b-u-p-r,j-r-b-u,v-u--" +
	"r-u,v,j--r--r-r-u-r-u-d-d,r,j-u-b-b-b-u-k-k,r-h,r-k,b-k,r-b--r--r--r-r,j-r--" +
	"r,rs-r,j-b-u,rs-b-u,j-r,j-b--u,j-d,b-d,u,v-k,b-k-k-k,b-k,b-k,b-k,u-h-h,r-k-k,r-b-u,j-b-u,v-b-u,v-rtp,u,rs-u,v,rs--" +
	"r,j-u--us,r-b--b-u-u--us--u-k-k,u-r,j--u,j-h,r,j-h,b,v-h,u-k,b-k-k-k-k,r-r,j--r,j--r--" +
	"r,j-r-b-u,v,rs-u,j-r,j---u,j-b-b,v-u-k-k,r-b-u,v-u-h-h,u-b-u,j-u,v-k,b-k,b-k-k,r-u--r--r--" +
	"r-b-b-u--r-b-u,j-b--u-k-k,b-k,u--u-h,r,j-h,u-r--r,j--r,j-c2,u-k-k-k,r-b-u,v-b-u,v--" +
	"r-i-i,r-b-r-b-u,j--u-r-k-k,r--u,rs-u,v,rs-h-h,u,j-b-u,j-b-u,bs-b-u-k-k-k-k-k,r-r,j--r--" +
	"r----u-r,j--r,j-b-u-k-k,r-u,v-b-r-h,r,j-u,j--r--r,j--r-k,b-k,b-k-k,b-k,r-u--r--" +
	"r-b-b-u--r,j-b-b-r-k-k-k,u--u,j-u-h-h,r-b-u,j-b-ext,u-b-u,j-b-u-k,u-dtp,r-k,b-k,r-b-u,v--" +
	"r,j-d-d-d,r,j-u-r--r,j-u-k-k,r-r,j-u,j-b-u-h-h,r--r--r--r,j-b-b-b-bl-dtp,u-k,b-k,r-r,j--" +
	"r-d,b-d,b-d,b-d,u-u,v-b,v-u-k,b-k,b-k,u-b-u,j-u,j-h,b-s,b-h,u,j-b-u,j-b-u,rs-b-u,bs,rs-b-b,v-u-u,j-b-u,v-k,u-u-";
var level10 = "-b-b,v-b-b-b-b,v-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b--" +
	"r---r---r,rs-d,b-d,b-bl,b-d,b-d,r-h-h-h,r-h-h-h,r,j-----r,j--r--r,rs-d,b-bl,b-d,b-d,r--" +
	"r-b-c1-r,rs-b-b-u,v-k,b-k,u-r-k,r-d,r-h,b-h,b,v-h,u,j-h,b-s-h,r-b-b-b-b-u--r-b,v-u---r-d,u,bs--" +
	"r-tp3,r-b-u---r---r-k,r-d,r-gt-gt-gt-gt,r-h-h,r---r--r--r,j--r--rtp--r--" +
	"r-tp3,r--r-b-b,v-u---r-k,u-d,r-gt-gt-gt-gt,r,j-h,b-h,u-b,v-b-u,v--r,j--r-b-u-b-b-b,v-u--" +
	"r-n,r,rs-b-u,v---r-b-b-u,v-d-d,u-gt,b-gt,b-gt,b,v-gt,u-h-h-h,r----r--p,r---r---r--" +
	"r-tp3,r--r---r,j---r,rs-d,u,bs--r---r-h,b-h,b-h,u,v-b,v--us-r--p,r---r--c2-r--" +
	"r-tp3,u-b,v-u-b-b-u-b-b-u-tp4,u--r,j--i-r,j--r-h-h,r-b,v-b-u,v,j-b-p,u-b-b-u-b-b,v-u--" +
	"r-k,r-i,n-n-n-n--r-b,bs---ds-r-b-b,v-u--r-h,b-h,u-h-h,r--r,j---r----r--" +
	"r-k,u-n,b-i,n,b,v-n,b-n,b---i,r-b-b-b-u-----r,j-h-h-s-h,r--ext,r--tp2-r,j----r--" +
	"r---r--r-ext,b--i,r,rs-n-n-n-n,traps,r-b-b-b-b-u-h,b-h,b-h,b-h,u--ext,r-b-b,v-u-b-b,v-b-u,v--" +
	"r-b,v-b-u---r-n-n,r-n-n-n-n,r,rs----gt-gt,r-k,u-h-h-h,r--ext,r--r--b-b-b-r--" +
	"r---r-b-b,v-u-n-n,r-n-n,sp-n-n,r,rs-b-b-b-gt-gt-gt,r-h,b-h-h,r,j--ext,r--r-r-k,b-k,b-k,u-r--" +
	"r---r,j---r-n-n,r-n,sp,b-n,b-n,b-n,u,rs-d,b-d,b-d,r-gt,b-gt-gt-gt,r-h,b,v-h,u--ext,r-b-u,v,j-b-b-b-b,bs-u--" +
	"r-b-b-u,v---r-n-n,r--p-r,j---r-bl,r-rtp,u,rs-gt-gt-gt,r--r--ext,r-h-h-h,r-n-n-n-n,r--" +
	"r---p,r,j-b-b,v-u-n,b-n,u-b-b-u,v-b-b-u,v-d,b-d,r-gt-gt-gt,r-b-u--ext,r-h-h,sp-h,r-n-ra,n-da,n-n,r--" +
	"r-b-b,v-u----r--rtp--r--r--r-d,r-st-st-st--ext--r-h,b-h,b,v-h,u-n-ua,n-la,n-n,r--" +
	"r-n-n,b-n,r--ra--r,j-b-b-b-u,v-b-r,j-traps-r-d,r-st-st-st----r-h-h-h,r-n,b-n,b-us,n,b-n,u,bs--" +
	"r-n,r-k,u-n,r-b,v-b-b-u--r---r-u-b-u-d,u,bs-st-st-st-b-b-b-u,v-h,b-h-h-h,r---r--" +
	"r-n,b-n,b,v-n-n,r---r,j--r,j--tp1-r,j--r--r-gt-gt-gt,r--r---r-h-h-h,r,j-b-b,v-u--" +
	"r--r-n,b-n,u-b-b-u,v-b-u,v-b-b,v-u-b-u,v-b,v-u-gt-gt-gt,r-b-u,j-b-b-u-h,b-h,b-h,u-h-h-h,r--" +
	"r--r--r-b,v---r---r-k-k,r---r-gt-gt-gt-gt-gt----dtp-dtp,r-h-h-h-h,r--" +
	"r-b,v-c1,u---r-b--r-b-b,v-u-k-k,r---r-gt-gt-gt-gt,b-gt,b-b-b-b-dtp,b-dtp,u-h,b-h,b-s,b,v-h,u--" +
	"r--r-b---r,j-b-u---u-k,b-k,u-b-b,v-u-gt,b,v-gt,b,v-gt,u,v-b-u,v--r--rtp--r,j-h-h-h,r--" +
	"r---r---ext--r--r-r-b---r--ext--ext-r-b-b,v-u-b-b,v-b-rtp,u-h,b-h,b-h,r--" +
	"r---u-b-b-b-b,v-u-b,v-u--r,j-b--r--p-p-p-r---r--r--r--r,j-h,u--" +
	"r-b-u,j-d-d-d,r--r-b--r---r-b-u--p-p-p-r-b,v-b-u,j-b-u--r,j---r--" +
	"r--r-d-sp-d,r,j---p,r-b-u,j-b-b,v-u--r--p-p-p-r-u,v-u,v,j-d-d-d,r-b-u,v-b-b,v-u--" +
	"r--r-d,b-d,b,v-d,u-b-b-b-u,v----r--r-----r-u,j-u-d-d-d,r-dtp-r---r--" +
	"r--p----u,v---r----r,j--r-b-u-st,u-b-u,bs-rtp,u,v-ra,u,bs,rs-sp,b-d,b-d,u--r,j---r--" +
	"r-b-b-b-b-u-b,v-b-b-u-b-b-b-u-b-u,rs-d,b-d,b-d,bl,b-d,b-d,u,rs-b-b-u,j-rtp,u-u,rs-b-u-b-b-u-";
var level11 = "-b,bs-b-b-b-b-b,v-b,v-b-b,v-b,v-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b,v-b-b--" +
	"r,j-st-st-st,r--r,rs-r-r-r-ua,u,v-i,r---r--r-b--r-k-k-k-k-k-k-k-k-k,r-st-st-st,r,j--" +
	"r-st-sp,st-st,r-b-u-da,r-r-b,v-u-r-b-b-u,j--u-st,r,rs--r-k-k,b-k,b-k,b-k,b-k,b-k,b-k,b-k,u-st-sp,st-st,r--" +
	"r-st,b-st,b-st,u,bs,j--r-u,v-r--u-r--u-st,r-u,j-st-st,r-b-u-k,u-st-st,b-st,b-st,b-st,b-st,b-st,b-st,u,j-st,b-st,b-st,u,v--" +
	"r---u,v--r-r-r-u,rs-u-r-r-st-st-st,b-st-st,r,j-r,j--r-st,r,rs-b-b-b-b-b-b-b-r,j-r-p,r--" +
	"r--u-r-b-u-ua,r-r-b-u,v-r-r-st,b-st,u,j-ext,r-st,b-st,u-r--r-st,r,j-b-b-b-b-b,v-b-r-r-u,v-r--" +
	"r-p,u--u,v--r-u,v-b,bs-b-b-r--r-ext-ext,r-b-b-u,bs-rtp,b-u,j-st,r--r,j--rtp,r-r,rs-r-r-r--u,v--" +
	"r--u-r-b-r-traps,b-traps,b--r-r-us-u-ext,b-ext,u,j-b-b-b-b-u,j-st,r-b-r-b-u,v-r-r-r-r-r-r--" +
	"r-u,j-b-ua,b-u,rs-u,rs--r-traps,b-traps,u,j-r-b-b-b-b-b-b-b-b,v-u,j-st,r-p,b-u-b,v-b-u-u,j-u-u,j-u-u--" +
	"r-b,v-b-b-b-b-b-b-b-b-sp-b-b---b-b-b-u-st,b-p,st,b-st,b,v-st,r-i,u,v-k,b-k,b-k,b-k,b-k,b-k,b-k,r--" +
	"r-d-d-d,b-d,b-d-d,sp-d-d-d,r-r,j--r-b-u,rs-r,rs-b--u,j--b-r-st,r--r--r,j--r-r-k,r--" +
	"r-d-d,r-k-k,r-d,b-d,b-d,b-d-d,r-r-b-b-b,bs-u,v--r-u,v--u-ext,r-u-st,r-b-u,j-b-u-b-u,j-i,u,v-k,r	w--" +
	"r-d-d,r-k,b-k-k-k-k,r-d-d,r--b,v-b-r-r-b-u--u-ext-ext,r-r,j-st,r--r--r,j--r-i,r-k,r--" +
	"r-d,sp-d-d,u-k-k-k,b-k,u-d-d,r-r-b-u-r-r-gt-gt,r-u,v-gt,r-ext,b-ext,u,v-r-st,r-b,v-u,j-b-u-b-u,j-u-k,r--" +
	"r-d-d,r-k,b-k-k,r-d-d,sp-d-d,r-r-tp2,u-st,r-r-u,v-gt-gt-gt-gt,r--r-r-st,r-r-b,v-r--u,v-r-k-k,r--" +
	"r-d-d-d,r-k,b-k,u-d-d-d-d,u-r-st,b-st,u,v-r-gt,b-gt,b-gt,b,v-gt,b-gt,u--r-r-st,r-b-u-u,j-u-b-u,v-k,b-k,u--" +
	"r-d-d,b-d,b-d,b-d,b-d,b-d,b-d,r-tp2,u-r-b,v-r-r-i-i-i-i-i,r-b-u-h-h-h-h-h-h-h-h-h-h,r--" +
	"r-d,r-b--u--r-rtp,r-d,b-d,u-i,u,v-r-u-u,v,j-i-i-i-i-i,r-h-h-h-h-h-h,b-h,b-h,b-h-h-h-h,rtp,r--" +
	"r-d,r--u--r-b-r,rs-b-b-u-b--r-i-i-i-i-i,r,j-h-h-h,b-h,b-h,u-k-k,b-k,u-h-h-h-h,r--" +
	"r-d,r-b--ra-da-r-p,u-h-h-h-h,r-b-u,j-i,b-i,b-i,b,v-i,b-i,u-h-h,r-k-k,b-k,b-k,u-h-h-h-h-h-h,r--" +
	"r-ds,r-r-b-ua-la-b-r-h-h-h,rtp-h-h-h-h-h-h-h-h-h-h,r-k,r-h-h,b-h,b-h,b-h,b-h,b-h,b-h-h,r--" +
	"r-h,r--r--u--u-h-h-h-h-h-h-h-h-h,sp-h-h-h,b,bs-h,u-k,r-h,r--utp----r,j-h-h,r--" +
	"r-h,r-c1,u-b,bs-u-b-b-u-h-h-h,b-h,b-h,b-h,b-h,b-h-h-h-h,r-tp1,u-k,b-k,u-h,r-b-utp,b-b-b-b-u,j-h,b,bs-h,rtp,u--" +
	"r-h-h-h-h,r-h-h-h-h-h,r--b-b-b,v-r-h-h-h-h,r-k,r-h-h-h-h-h-h,r,rs-h-h,r-h-h-h,r--" +
	"r-h-h-h-h,r-h-h-h-h-h,r-r,j--r-r-r-h-h-h,sp-h,r-k,r-h-h,rtp-h-h-h-h,r-h-h,u,v-h,b-h,b-h,u,v--" +
	"r-h-s-h-h-h-s-h-h-h,r-r-b-u-u,v-r-h-h-h-h,r-k,r-h-h-h-h,sp-h-h,r-h,rtp,u-b-u,v-b,v-u--" +
	"r-h-h-s-h-h-s-h-h,b-h,u-r-r--r,j-r-h-h-h,b-h,u-k,r-h,b-h,b-h,b-h-h-h-h,r-b,v-u-b-u,v--" +
	"r-h-h-s-s-s-h-h,r-b-r,j-r,j-u-b,v-u,v-r-h-h,r-k,b-k,b-k,b-k,b-k,b-k,u-h-h-h,sp-h,r-b-u,v-b,v-u--" +
	"r-h-h-h-s-h-h,b-h,b-h,r-r-r--r-r-r-h-h-h-h-h-h-h-h,sp-h-h-h-h,r-b,v-u-b-u,v--" +
	"r-h,b-h-h-h-h,r-st-st,r-h,r-u,v-r-b-u-r-r-h-h-h-h,sp-h-h-h-h-h-h-h-h,r-b-u,v-b,v-u--" +
	"r-p,u-h,b-h,b-h,b-h,u-st,b,v-st,u,v-h,u-da,u,v-u,v,j-b-b-u-u-h,b-h,b-h,b-h,b-h,b-h,b-h,b-h,b-h,b-h,b,sp-h,b-h,u-st,b-st,i,u,v,j-b-u-";
var level12 = "-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b,v-b-b-b-b-b-b-b-b--" +
	"r-r,j--r--r--r,j-u,v--r,j-r-b,v-b-r,j-r-k,b-k,u-h-s,r--r-sp,u-b-r-r,j---b-r-k,u--" +
	"r-ext,u-b-u,v-c2,b,v-p,u,v-b,v-u-r,j--r,j-u,v--r-u-b-b-u,j-h-h,r,j-b,v-u,j--r,j-r-r-b,v-st,u-k,u	-b-u,v--" +
	"r--u,j-b,v-sp,b,v-sp,b,v-u,v,j-b-u-b-r,j-r-b--u--b-u-h-h,r--r-b-u-u,v,j-sp,r--r,j---r--" +
	"r-u,v--r-c2-p,r--r-r,j-r-u,j-u,v-r,j-u-p,r-p,u-h-h,b-h,b-h,r-b-u,j---r-r-b-u,v-b-b,v-u--" +
	"r-r,j-b-u-b-u-b-u,j-u-r-k,u-b,v-u-b-sp-u,j-h,r-tp4,u,v-k,u-h-h-h,r-b-b-u-r,j--r-d-d-d,r--" +
	"r,j--r,j-b-b-u,j---s,r-bl,r-ext,r--u-r-p,u,v-k,u-h,u-p,u,v-s-h-h,b-h,u--u,j-r-r-b,v-u-d,b,v-d,b-d,u,j--" +
	"r-b,v-u-k,b-k,b-k,u-b-b,v-u-r,rs-u,rs-u,j--u-u,j-u,j-u,j-p,u-h-h,r,j-b-r-r-k,u-r-r--r---u--" +
	"r-r,j-b-b-sp,b-b-u,j--r-r-k,r--u-h-h,r-b-u-u-h-h-h,r-u,j-u,j-b-u-u,v-b-u,v-b-u,j-r--" +
	"r,j--u-k,b-k,b-k,u-st,b-b-u,j-u,v-k,r-u-s-h-h,b-h,b-h,b-h,b,v-h-h-h,b-h,u,j-b-b-b-b-r--r--r,j--" +
	"r-u,j-b-b-i,b-b-u,j-b-r-h,r-k,b-k,u-h-h,r-b--b-u-s-h,r--r--r--s,r-r-b,v-u-b-u--" +
	"r,j-b-b-b-bl,b-b-u,j-h,r-u-h-h-h-h,b-h,u-r-u,v-st-st,r,j-h-h,r-b-u,j-i,b-u,j-b-u,v-u,v-r-k,u-b-r,j--" +
	"r-u--r,j-d-d-d,r-h-h,r,j-h,b-h,b-h,u-b,v--b-u,j-st,b-st,u-h-h-h,r---u,j-b-b--r,j--,r,j-r--" +
	"r-h,u--r,j-d,b-d-d,r-s-h,r-h-r--r,j-u-h-h,r-h-h,u,j-h,b-h,b-h,u,v,j-b-r-k-k-k,r-b-u,v-b-u-r--" +
	"r-u-b,v-u-h,r-d,b-d,u,j-h-h,u,v-b-u,j-b,v-u-h,r,j-h,b-h,r,j-h,r-k,b-k,b-k,u-d-d,r-u-k,b-k,b-k-k,r-r--u,j-u--" +
	"r--r-r-h,b-h,b-h-h,r-r--r-r-h-h,r-k,u-h,r-h,b,v-h,b-h,u,j-r,j-sp-sp,r,j-u,j-la,u,j-dtp,u-k-k,u-r-r--s,r--" +
	"r,j-b-u,v-r-d-d,r-h-h,r-r-us,b,v-u,j-r-h,b-h,b-h,u,j-h,u-i,r-b-b-u-d,b-d,u,j-r-k,b-k-k,u-b,v-u-u,j-b-u,j--" +
	"r-i,r--r,j-d,b-d,sp,u,j-h-h,r-u,v-r-b-traps,b-u,j-d,r-i,b,v-i,b-i,u-h-h,r,j-h-h-h,r-b,v-u-k,u--b-b-b-b-ext,u--" +
	"r-r-b-u-s-h-h,b-h,u-r-r-h-h-h,r-d-d,r-h-h,r,j-h-s,r-h,b,v-h-h,u--r,j-b-u-h,r-h-h-h-h,r--" +
	"r-b-r,j-r-h-h,r-r-h-r-u,v-h-h-h,u-d,b-d,u,v,j-s-s,r-h,b-h,u-r-s,u,v-k,u-b-u,v-h-h-h,r-h,b,v-s,b-h,b-h,u--" +
	"r-tp4,u-u-r,j-h-h,r-r,j-b-u,j-r-h,b,v-h,u,j-u,j-i,b-i,u-h,b-h,u-ext,b-b-r-h-h,b,v-h-h,u,j-h,b-h,b-h,b,v-h,u-b,v-b-r--" +
	"r-h-h,r-u-h-s,u-r--r-r-h-h-h,b-h,b-h,b-h,b-h,u--r,j-u-h,r-r-h,r-k,b-k-k,r-b-b-b-r-u,v--" +
	"r-h-h,r,j-h-h,r-b,v-u,j-b-r-bl,r-h-s,r-k,u-u,v,j-b-r-b-b-u,v-h-h,r-u,v-h,b-h,r-k-k-k-k-k,r-r,j-r--" +
	"r-s,b-h,u-h,b-h,u-b--r-r-r,j-h,b,v-h-h,r-bl,u,v-rtp,u,v-u,j--r-r-h,b-h,r-b-u,v-h,r-k-k-k-k-k,r-u-u,v--" +
	"r,j-u,j-b-r,j-u-r-b,v-u-u,v-c3-r-h,b-h,u-r-r-k,r-b-u,j-b-u,j-h,b-h,b-h,b-h,u-k,b-k,b-k,b-k,b-k,u-ext,b-u,v,j--" +
	"r-i-r,j-u,v-r-r--i,r-r-b,v-u-h-h,r-r-r-k,r-r,j-b-b,v-u,j-r,j--p-u,j-b-u,j-u,j-b-u,j-u,j-r--" +
	"r-b,v-u-b-u,j-r-b-u,j-r-r-h-h-h,r,j-u-u,v-k,u-b-u,j-u,v-ext,b-u-b-u-r,j--r--r--r,j-u,v--" +
	"r-b-r-k,r-r,j-u,j-b-b-r-r-h,b-h,b,v-h,u,j-h,r,j-b-b-b-b-sp,b,v-b-b-b-u,v,j-u-b-u,v-tp3,b,v-u,v-b,v-u-r--" +
	"r-r,j-u-k,u-u,bs-k-k,b-k,u-ext,u-b-u,j-r-h-h,r-k-k,b-k,u-u,j-ua,u,j-u-k,b-k,u-r--u,j-b,v-sp,b,v-sp,b,v-u,v,j-b-u--" +
	"r-b-u,j-p,b-u-k,u-tp1,u,j-b-u,j-b-u,j-u,v-h-h,r-k,r-rtp,b-u,j-p,b-u,j-b-ds,u,j-tp2,u-r-u,v--r-ds-p,r--r-ext,r--" +
	"r-rtp,b-u,j-b-u,j-b-u,j-b-u,j-b-u,j-u-h,b-h,u-k,b-k,b-k,b-k,b-k,b-k,b-k,b-k,u-u-u,j-b-u-b-u-b-u,j-u-";
var level13 = "-b-b-b-b-b-b-b-b-b-b-b-b-b,v-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b,bs--" +
	"r,j-b-b-r-r,j-b-r-b-r,j---u,j-r-r,rs-b--u--r,j--r--rtp,u--r-r,j-b-r---r--" +
	"r--r-r--r,j--r,j-r-b-u--r-r-k,r-u,v-r,rs-b-r-st,b-u,j-b-b-u-b-u-k,r-r-b,v--r--" +
	"r--u,v-r-rtp,b-u,v-b-st,u-b-u,v-d,r-b-r-r-k,r--u-k,r-u-k-k-k-k-k,b-k,b-k,b-k,u-b-u-b-u,v--" +
	"r-u-b-b-r-b--r,j-r-d-d-d,u-u,v-r-k,r-u-k-k-k-k-k-k,b-k,u--b-b,v-b-r-b--r--" +
	"r---r,j-b-r--u-r,j-d,b-d,u,v--r-r-k,b-k-k-k-k-k-k,u--b-u-ext,r-d,r-sp,r-b-r-b-u,v--" +
	"r--b,v-u,j-r-r-rtp,u-b,bs-u-d-d,r--u-r-r-k,b-k,b-k-k-k,u--u-ext-ext-ext,u-r,j-sp-sp,r-b-r-r--" +
	"r-p,r-b-b-u,v-b-b-b-r-d,b,v-d,u-u,v-r-r--b-r-k-k,r--u-ext-ext-ext,r-d-d,u-sp,b-sp,b-sp,u-r-da,u,v--" +
	"r-rtp,u---u-k-k,b-k,r-b--r--r-r-r-r-r-k-k,r-r-ext,b-ext,b-ext,b-ext,u,rs-d-d,b,v-d,b-d,b-d,u,j-r-ua,r--" +
	"r-r,j-b-p,u-k-k,u-h,r-k,b-k,r-b-r-b-u,v-r-r-r-r-k-k,r-r,j-d,b-d,b-d,b-d,b-d,r-ua-la-da-ra,r-r-u,v--" +
	"r--r-k-k,u-h-h-h,r-k,b-k,r-b-u,v-r-r,rs-u-r-r-k-k,r-r-i,b-i-i-i,r-d,r-da-la-ua-ua,r-r-r--" +
	"r-b,v-rtp,u-k,r-h-h-sp-h-h,r-k,b-k,r--r-r--r-r-k-k,r-b-r-i,b-i-i,r-d,r-la-da-ra-c2,u-r-u,v--" +
	"r--r-k,r-h-sp-h-h-h-h,r-k,r-p,b-r-r-r-r-r-k,b-k-k,r-b-r-i,b-i,r-d,r-ua-ra,b-ua,u--u,bs-r--" +
	"r--r-k,r-h,b-h-h-s-s-h,r-k,b-k,r-p,u-ua,r-r-tp4,u-b-r-k-k-k,r-b-r-i,u-d,u,v-ua,u,rs--b-u--r--" +
	"r-b-u,v-k,b-k,r-h-s-s-s-h-h,r-k,b-k,r-ua,u-b-b-b-u,bs-k,b-k,b-k,b-k,u-b-b-b-b-u-b,v-u,j-b-u--" +
	"r-da,r--r-k,r-h,b-h-s-s-s-h-h,r-k,b-k,b-k,b-k,r-ra,b-ra,b-b-b-b-b-b-b-b-b-b-b-b-b,bs-u,j--" +
	"r-r--r-k,b-k,r-h,b-h-s-s-s-h-h-h-h,r-k,b-k,b-k,b-k,b-k,r-b--r,j-traps-traps-traps,r,j--r---r--" +
	"r,rs-r-b-b,bs-u-k,b-k,r-h,b-h,b-h-s-s-s-h-h-h-h-h-h,r-k,b-k,r-b-ds,u-traps,b-traps,b-traps,u,v--u,j-b-b,v-u,bs,rs,--" +
	"r-b-b-b-tp3,b-tp3,u-k,b-k,b-k,r-h,b-h-s-s-h-s-s-s-s-h-h,r-k,b-k,r--r--r-u-b,v--u-r--" +
	"r-c1,b-i,b-i,r-st-r-i,b-i,r-k,b-k,r-h,b-h-s-h-h-s-s-s-h-h-h,r-k,r-b-u,v-b,v-u,j-h-h,r-r--r--" +
	"r-i-i,r-i,r-r-b-r-i,r-p,r-k,b-k,r-h-s-s-tp2-s-h-h-h-sp-h,r-k,b-k,r--r-h,b,v-h-h,r,j-r-b-u,v--" +
	"r-i,r-i-b-b---r-p,b-r-k,r-h,b-h-s-s-s-s-h-sp-h-h-h,u-k,r-b,v-u-r-h,b-h,u,v-b-b-r--" +
	"r-i,b-i,r--b-r-b-b--u-k,b-k,r-h-h-h-s-s-s-h-h-h,r-k-k,u-r-rtp,b--r---r,j-u--" +
	"r--b-b-r--b-b-r-s-d,r-k,r-h-h-s-s-s-s-s-h-h,r-k,r---rtp,u-b-u,bs-b-b,v-u,j-r--" +
	"r-b-r--b-r-tp2,b-sp-r-s,u-d,r-k,r-h,b-h-h-s-s-s-s-h-h,u-k,r--u,rs---r-d-d-d,r-r--" +
	"r-ext,r-b-u--b-u--sp-d,r-d,r-k,b-k,r-h,b-h-h-s-s-h-h,u-k-k,u-u,v-b--b-r,j-d-sp-d,r,j-u--" +
	"r,j-ext-ext-ext,r--b-r-sp-r-d,b-d,u-tp1,r-k,b-k,r-h,b-h,b-h,b-h-h,r-k-k,u-p--p,r-rtp,u-r-u-d,b-d,b,v-d,u-st,r,j--" +
	"r-ext-ext,b,v-ext,u-r-b--b-b--u-tp1,r-sp,r-k,b-k,b-k,b-k,r-h,b-h,u-k,r-p,b-p,b-b,v-p,u--r,j--r-st-st-st,r--" +
	"r-ext,u-r--b-u-u--b-r-r,rs-r-sp-sp,b,bs-sp-sp,u,v-k,b-k,b-k,b-k,u--r--r,j-b-u,bs--r,j-st-st,b-st,u--" +
	"r,j--r-b-r-st-b-u-r--u-r,rs-sp,r,rs-p,u,bs,rs-sp,r-r--r--r-us,b,v-r,rs--r--r-us,b-r-st,u,v--r,j--" +
	"r-b-b-u-b-b-b-b-b-b-u-u-sp,b-sp,b-sp,u-b-u-u,j-b-b-u-u-b,v-u-b-b-u-b-u-b-u-";
var level14 = "-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b,bs-b-b-b-b-b-b-b-b,bs-b-b-b-b-b--" +
	"r--b-b-b-b-b,v-b-b-b-b-r-sp-d-d,b-d,b-d-d-d-d,r--b-b-b-b-b,v-b-b-b-b-r--" +
	"r-r-b,v-u,j-b-u,j-u,v,j-b-u,j-b-u,v-r-d-d,r-tp4-st,r-d-d-d-d,r-r-r,j-b-b-u,rs-u,v,rs-b-b-u,j-r-r--" +
	"r-bl,r-r--b-u,bs,j-u,v,j-b,bs-b-r-r-r-d-d,r-b-u,v-d-d-rtp-d,r,j-r-u,v--b-u,v-r-b,v-b-r-u,v-r--" +
	"r-r-r-r-r-u,bs-u-u,bs-r-r-r-r-d,b-d,b-d-d-d-d-d,b-d,u-r-r-r-b-u-r-b-u-r-r-r--" +
	"r-r-u,bs-u,j-u-b-b,v-u-u,j-u-u,bs-r--r-d-d-d-d,r--r-r-u,v-u,v,rs-u,rs-r-u-r,rs-u,rs-u,v-u,v-r--" +
	"r,rs-r,j-u,bs,j-b-b-u-tp3,u,v-b-b-u,j-u,bs,j-r,j--dg,r-d-d-d-d,r-dg-r,j-r,j-u,v,j-dg,u,v,j-u-r,j-u,j-r-u,j-u,v,j-u,v,j-r--" +
	"r-r-r-r,j-r-b,bs-b-u,bs-r,j-n,r-r-r-b-u-d-d-d-d,r-b-u-r-r-n,r,rs-u,rs-u-r-u,rs-u,rs-r-r-r--" +
	"r-r-r-r-u-u,bs-u,v-u,bs-u-n,r-r-rtp,r-d-d-d,b-d,b-d,b-d-d-d,r-rtp,r-u,v-n,r-b-u,v-r-b,v-u-r-u,v-r--" +
	"r-r-u,v-b-b-u,j-u,v,j-n,b-n,b-n,u-u,v-r-d-d,u,j-h-h-h,r-d,b-d,b,v-d,r-u-r-n,b-n,b-n,u-u,v-b-b-u-r-r--" +
	"r-r-b-u,j-b-u,j-u,v,j-b-u,j-b-u-rtp,u,v-d,u-da,u,v-h-h-h-h,n-h,n,r-d-d,r-u,j-b-b-u,rs-u,v,rs-b-b-u,j-u-r--" +
	"r-b-b-b-b,v-b-b,v-b-rtp,b-u-h-h-h-h-h-h-h-h,n-h,n,r-d-d-d,r-b-tp2,b-b-b,v-b-b-b-b-u--" +
	"r-d-d-d-d,r---r-n-n,b-h,b-h-h-h-h-p-p-h,n-h,n,r-d,b-d,b-d-d-d,r---r-d,n-d,n-d,n-rtp,n,r--" +
	"r-d-d-d-d,r-b-dg,b-u-n,r,j-b-u-h-h-h-h,n-h,n-h,n-s,n-sp,n-h,n-h,n,r-d,b-d-d,r-b-dg,b-u-d,n-d,n,b-d,n,b-d,n,r--" +
	"r,rs-d-d-d-d-d,r,rs-n-n,b-n,u-h-h-h-h-h-h,n,b-h,n,b,v-h,n,b-h,n-h,n-h,n-h,n,r,j-u-d-sp-d-d-d-d,n,r--r-d,n,r--" +
	"r-d-d-d-d-d,r-r,rs--r-h-h-h-h-h,u-rtp-r-r-h,n,b-h,n,b-h,n-h-h,r-d-d-d-d-d-d,n,r,j--st,r-d,n,r--" +
	"r-d,n-d,n-d,n-d,n-d,n,r-n,r-b-u,v-h-h-h-s,r-r-b,v-p,u,rs-r,j--dg,r-h-h-h,r,j-d-d-d-d-d-d,n,r-b-u-d,n,r--" +
	"r-d,n-d,n-d,n-d,n-d,n,r-n,r--r-h-h-s-h,r-b-r-b-u,v-b-u-h-h-h,r-us-d-d,b-d,b-d,b-sp,n-d,n-d,n-d,n,r--" +
	"r-d,n-d,n-d,n-d,n-d,n,r-n,r-b,v-u-h-h-h-h-h,r-b-u-h-h-h-h-h-s,r-d-d,r--dg-r-d,n-d,n-d,n-d,n,r--" +
	"r,rs-d,n,b-d,n,b-d,n,b-d,n,b-d,n,u-dtp,n,r-u-u,j-h,b-h-h-h-h-h-h-h-h-h-h-h-h,r,j-d,b-d,u-b-b,v-u-d,n,b-d,n,b,v-d,n,b-d,n,u--" +
	"r--ext,b-s,b-s,b-s,u-dtp,u-k,b-k,b-k,u-h,b-sp-h-h-p-p-h-h-h-h-h-h,u-b-rtp,b-b-b,v-b-b-b-b-r--" +
	"r-r-r,j-b-b,v-u,rs-u,v,rs-b-b-u,j-r-h,b-h,b-h-p-p-h-h-h,b,v-h,b-h,u-b,v-u,j-b-u,j-u,v,j-b-u,j-b-u,v-r--" +
	"r-r-u,v--b-u,v-r-n,b,v-n,b-n,r-u,v--rtp,u,j-h,b-h,b-h,b-h-h,r-ua,u-k,r-r-r-n-n,b-n,u,bs,j-u,v,j-b,bs-b-r-r-r--" +
	"r-r-r-r-b-u-r-b-u-n,r-r-rtp,r-k,b-k,b-k-k,u-h,b,v-h,u-k,b-k,u-rtp,r-r-n,r-r-u,bs-u-u,bs-r-r-r-r--" +
	"r-r-u,v-u,v,rs-u,rs-r-u-r,rs-u,rs-n,u,v-u,v-r--r-k,r-d-d,r-k,r--r-r-u,bs-n,u,j-u-b-b,v-u-u,j-u-u,bs-r--" +
	"r-r,j-u,v,j-u,v,j-u-r,j-tp1,u,j-r-u,j-u,v,j-u,v,j-r,j--dg,r-k,r-d-d,r-k,r-dg-r,j-r,j-u,bs,j-b-b-u-u,v-b-b-u,j-u,bs,j-r,rs--" +
	"r-r-r-r,rs-u,rs-u-r-u,rs-u,rs-r-r-r-b-u-k,r-d-d,r-k,r-b-u-r-r-r,j-r-b,bs-b-u,bs-r,j-r-r-r--" +
	"r-r-u,v-r-b-u,v-r-b,v-u-r-u,v-r-k,b-k,b-k,u-d-d,r-k,b-k,b-k,u-r-r-r-u-u,bs-u,v-u,bs-u-r-r-r--" +
	"r-r-r-b-b-u-u,v-b-b-u-r-r,j-d-d-d-d-d-d-d-d,r-r-u,v-b-b-u,j-u,v,j-b-b-u-u,v-bl,r--" +
	"r-r-u,j-b-b-u,rs-u,v,rs-b-b-u,j-u-r-d-d-d-rtp-d-d-d-d,r-r-b-u,j-b-u,j-u,v,j-b-u,j-b-u-r--" +
	"r-b-b-bl,b-b-b-b,bs-b-b-b-b-u-d,b-d,b-d,b-d,b-d,b-d,b-d,b-d,u-b-b-b-b-b-b-b-b-b-b-u-";
var level15 = "-b-b-b-b-b-b-b-b,bs-b-b-b-b-b-b,v-b,v-b,bs-b-b-b-b-b,v-b-b-b-b-b-b-b-b-b--" +
	"r,j-la,b-la,u,bs,j-la,b-la,u,rs-ra,b-ra,u,j-ra,b-ra,u,j--p,r-k,r-h-h-h-h-h,u-n-n,b-n,u,j-bl,r-ua,b,v-n,b-sp,b-sp,b-n,b-rtp,u--b-r-n,u--" +
	"r,rs-r-b-b-r-la-ua,u,j--st,r,rs-b-u,v-k,r-h-h-h-h,u-s,r-n,u-bl,b,bs--b-u-k,u-b,v-b-b-u,v-u,bs-n,u-b-bl,u,v--" +
	"r,j-r-n,b-n,u-u,v-da,b-ra,r--p,r-d-d,r-k,u-h,b-h-p,r-s-s,u-k,u-r,j-u-tp3,u,j-b--u--u--r,j-tp4-bl-sp,r--" +
	"r,rs-u,j-u,j-b-u-ua-ra,u-b-u,rs-d,b,v-sp,u,v,j-sp,r-k,r-h-h-st,r-k,r---b-r-k,u-u,v,rs-ra-r-b--bl,r-d,b-st,b-d,u--" +
	"r,j----tp2,u,v-la,b-da,u,j-r-k,u-r-sp-ext,u-k,u-h-h-h,u-k,u-b-u,v-r,j-b-u,v-r-st,b-b-u-b-u,j-st,u-n,b-n,u--" +
	"r,rs---u,bs,j-ua,b--st,r--r-r-ext,u-bl-sp,r-h-h,b-s,u,v-r-k,u-b-st-u-r--r-n-n,p--r-rtp,u,v--p,r--" +
	"r,j-b-p,u-bl-la,r--r-p,b,v-u,v-b-u,j-h-h,r-h,r-h,r,j-b-bl,b,v-r-k,u-sp,r,j--r--sp,r,j-n-n,r,rs--p,r,j-b--r,j--" +
	"r,rs--rtp,r,j-b,bs-u,v-b-b-ua,u,j---u,rs-h-h,r-h,b-h,r-h,n-h,n,r-b-r-u-b,v-p,u-b-b-n-n,r---r,rs-b-u--" +
	"r,j---u,v,j-b-b-r,rs-b-b,v-r-s-h-h,r-h,n,b-bl,n,b-h,n,b-h,n-h,n,u-r-bl-r--b-r-n,b-n,u-p,b,bs-b-u-k,u-n,r--" +
	"r,rs-b-u,j-ext--u--b-p,u-u,j-h-h,b-h,u-h-h,b-h,r-h,n,u-bl,b-r,j-ua,b-u-r-k,u-b,bs-b-b-r-k,b-k,u-tp1,r-n,u--" +
	"r,j--r,rs--r,j-rtp-r--b-r-h,u-h-h,b-h,u-k,u-h,b-h,b-h,r-u,bs--b-u--r,rs--r-b-b,bs-u--u,j--" +
	"r-b-r--r-b-u,bs-r-k,r-h,b-h,b-h,u-k-k,u-sp,u,bs-k,u-h,n,r-h,b-b-r-p-la-ra,b-p,u-b-b-st,r,j-b-b-u-k,u--" +
	"r-n,u-r--r-k,u--u-k,u-h-rtp-h,r-k,r-ua-ua,b-h,n,b-h,n-h,n-h,n,r,rs-bl,r,rs-b-u-la-ua,r-ua-ra,r-rtp,u-k,b-k,b-k,u-r,j--" +
	"r-b-p,u,j-b,v-b-u,rs-bl,r,rs-h,b-h-rtp-sp-h,r-k,r-la,b-ua,r-k,r-h,n-h,n-h,n,r-b-b-r-da,u,v-la,b-ra,u-da,u,v-k,u-b,v-b-b-r,rs--" +
	"r,j-b-r-b-u,bs-k,u-b-r-h-h-h-h,r-k,r-la-da,u-k,u-h,n,b-h,n-h,n-h,n,r-n,u-bl,r,rs-ua,r,rs-r----r--bl,r-u,j--" +
	"r-bl,u,rs-b-r--r-k,u-r-h-h-sp-h,r-k,u-da,b-da,b-r-k,r-s-h-h-h,r-r-ua,u,v-r-b-rtp,b,v-b,v-bl,u--da-r--" +
	"r--r,j-r--r-utp,r-r-h,b-h-h-h-b---u-k,u-h-h-h-h,r-r-ua,r-r,j-b-r--ext,u-b--r--" +
	"r--r,rs-tp2,u,v-b-r-utp,r-b-h,r-h,b,bs-sp,b-h,u-k,r-r,j-rtp,u--b-h-s,b-h,b-h,u-bl,r,rs-ua,u,v,rs-p,u-r-u,j-u-n,b,v-n,r-b-st,u--" +
	"r,rs--r-r-n,u-bl,u-r-k,u-h,b-bl,b,bs-h,b-r-k,r-r--u-k,r-s,u-h-h,b-b-u,rs-da,r,rs-rtp,b----u-n,b-n-n,r,rs--" +
	"r,j-p,b-u--p,b-bl,r-r-p-h-h-h,r-r-k,r-b-u-k,b-k,u-h-h,u-s-h,r-k,u-da,u,v-k,r---u--r-n,b-n,u,j--" +
	"r,j-r,j-b--u,rs-bl,b-b,v-b-h-h-h,u-r-k-k,b-k,u--b-h,u-h-h-h-h,r-da,r-k,u--u,j---r-sp,b,v-ext,r--" +
	"r--r-u,v-h,b-bl-st-h-h-h,r,rs--r-k,u--b-u,bs-p,r-p,b-h-sp-h-s,r,rs-da,u,v,rs-tp4,u-u,bs-p,r-b,bs-p-u,rs-r,j-sp,u--" +
	"r--b-p,b,v-tp4,u,v-bl,b-h,b-h,b-h,b-h,u-bl,u,rs-b--u-rtp,b,v---u,v-h-sp-h-h,b,bs-h,r-k,u--st-r,j-u--u-bl,r--" +
	"r,j-u,j-tp3,b-b-u-bl,u-h,n,u-k,b-k,u-rtp,n,b,v-n,u-k,u-r-st-i,r,rs-b,v-u-r-h-sp,r-bl,b-st-bl,u-sp,r-b,v-b,v-p,u,v-b,v-u--r,j--" +
	"r-sp,b-b-sp,r-h,n,u-bl-h-h-st-h,u-k,u-b-u-i,b-i,r-r-b,v-u-h,b-h,r-h,b-bl-h,u-bl,b,v-sp,u,v-tp2-p,b,bs-r-k,r--r,rs--" +
	"r-st-sp-u-h-h,r,rs-h,b-h-h,r--sp-b-r,j-ext,r-i,u,j-r-b--r-h-h,r-p,u-h-h-h,r,j-r,rs-bl,u,bs,rs-r-k,r-b-r,j--" +
	"r,rs-b-u-k,r-h-h-h,r-h,b-h,r-sp-st,b,bs-bl-p,u-b,bs-u,bs-b-r-p,b-r-h,b-h-h-h-h-h,r,j-b-p,b,v-u-k,u-r,rs-u--" +
	"r-h-h,r-k,sp,u-h-h-h-h-h,r,j-rtp-b-r,j-la,b-la,u-ra,b-ra,u,j-b-tp1,u,j-u,j-n,r-h,b-h,b,v-h-h,b-h-s-h,r-k,r--u-r--" +
	"r-h-h-h-s-h-h-h-h,u-sp--b,bs-p,r,j--u,rs---r-n-n-n,r,j-rtp,u-bl,b-h,r,rs-h-st-h,u-k,u-u,v,j--r--" +
	"r,rs-h,b-s,b-h,b-h,b-h,b-h,b-bl,u-sp,u-b-sp,b-b-u,j-u,j-p,b-la,b-b,v-u,v-n,b,v-n,b,bs-n,u,v-h,n,b-h,n,u-st,u-h,b-h,u,v-k,u-rtp,b-la,b-p,b-u,v,rs-";
var level16 = "-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b-b--" +
	"r-p-b,bs-u,j-b,v-u,rs-b--r-k,b-k,u-b,n-b,n,r-k,u-h-h,r,rs-r-k,b-k,u-b,bs-b,v-u,bs-k,r-d-d,b,v-d-d,u,rs--p,r--p,r--" +
	"r-rtp,r-b-r--st-r,j-b-u,j-h,r-b,ra-bl-bl,r-h-h-s,u-r---r-b,bl-r-k,u-d,r-r-rtp,u-r--r,j-b,v-r--" +
	"r-u-r,rs-r-b,ext-b,ext-b,ext,r-r-s,b-h,b-h,r,j-b,st-h,r,b,rs-h,b,v-h,u-n,u-sp,r-b,bs--p,r-n,r-b,bs-r,rs-d,u,bs--st,b-r-p-r-r-u,v--" +
	"r--r-b-tp1,u-d-d,r,j-u,bs,rs-r,j-p,r-h,b-h,u,rs-h-h-s,u,j-bl,u,v-r-r-b-u,bs-n,u-bl,r,j-r-n,r-u-k,r-u,j-b-u-r-r--" +
	"r--u-k,b-k,u-d,b,v-sp,u-r-u,rs-u,j-n,r-k,r-h,b-h,u,j-h,b-h,u,bs-u,rs-u-k,r-h,r-b-r-r-n,r-k,b-k,b-k,b-k,u--u-da,u,v--" +
	"r-u,v,rs-b--r-d,b-d,r-r-n-n-n,r-k,u-b,v--r-r-k-k,b-k,u-h-p,r-r,j-u,j-n,b-sp,n,b-n-n-n,u,j-u-sp-d,u,v--" +
	"r-r-k,u-b-b-u,j-d,u-r-n,b,v-n,b-n,b-rtp,n,u,v-r-p-r-r-k,u-h,r,rs-h,b-h-h,r-b-u,v-k,u-r-n,b-n,r-d,b-sp-sp,u-ua,r--" +
	"r--r,j-da-st--da,r,j-u-r-b-b-p,r-r-tp3,b-u,rs-u-h,b,v-st,u-k,u-p,b-h,b,v-s,r-u,j-b--r-n,u-n,r-d,u-bl,r-u,v--" +
	"r-p-r-b,v-b--p,u-k,u-u,j-ra,b-la,u,j-r--r-h-h,b-h,u-k,r-d-d,b-d,u,j-s,u-k,b-k,u-tp1,b-r-r-n,u-bl,b,v-la,r,j-r--" +
	"r-b,v-b-bl,u-n,u-rtp,u-k,u--r,j-u,j-b-r-p,b,v-r-st,r-k,b-k,b-k,u-d,u,bs--u,j-b,v-b-r-k,r-r--bl,r,j-u,v,rs-u-u,bs--" +
	"r-st,b-u-n,u-k-k,r-rtp,r-b-u,v-k,b-k,u-rtp,u-r,j-u-h,b-h,b-h,u,rs-h-h,u-u,v-b-st-u-r-k,r-u,rs-b,v-ua,u-r-p-r--" +
	"r-k,b-k-k-k,b-k,u-ua-st,r,j-b-r,j--r,rs-u,j-ra-ra,b-rtp,u-p-h,u,v-b-u,bs-k,r-r-k,r-r-k,r--r-k,u-r--r--" +
	"r-r-k,b-k,u-rtp,b-la,b-sp,b-ra,b-rtp,u,j-ext,u,j-b-u-rtp,n,r-r-s-s,b-h,u,j--u,j-n,r-k,u-tp4,u-k,u-u,v-k,u--p-u-r-rtp,b-u,v--" +
	"r-st,u,rs--ext,u--u,j-la,b-b-ra,u,j-b-b,bs-r-n,u-r-s,u--b-u-k,u-n-n,u-k,u-r--ext,r-b,bs-u-h,r-st,b-b-u--" +
	"r-k,u-r,j-b-u-r,j-ra,b-b-la,u,j-b,v-u-r-bl,u,v--b-u,v-k,b-k,u-n-n,u-da,r-b-r---u-sp-p,b,v-s,b-h,b,bs-h,r--" +
	"r-rtp,r,j-r-rtp,b,v--r-r-k,u-s,r-r-traps-u,v--r-k,r--us,u-n-n,r-ra,b-sp-st,r,j-u,v-ext,b-r-h,b-sp,u-h,b,v-h,b-h,u-h,u,v--" +
	"r-ua,r,rs-u-r,rs-b-u,j--u,j-h,r-r-traps,u,bs-st,r-b-r-k,r-r-n,b,v-n,b-n,u-k,r-sp,b-u,v-b,bs-r-ext,u-k,r-h-h-s,r-k,r-ua,r--" +
	"r-r-st-u-k,u-ext,r-r-h-h,u--r-r-k,u-r-k,u-us,u--u-k,b-k,b-k,u-d,r,j-r-u-k-k,r-h-sp-s,r-k,u-ua,r--" +
	"r-r,j-u-k,u--r-u-h,u,v-tp3,b-b-r-r-b-b--r-r-k,u-sp,b-sp,b-sp,u,rs-d,r-r-k-k,b-k,u-h,b-h,b,v-s,u-h,r,j-la,r--" +
	"r---u,rs-b-u,v-s,r-h,b,bs-h,u-d,r-u,j-u-k,b-k,u--u-b-u,v-sp,b-sp-sp-d,r-r-k,r-b,v-u,j-h,b-h,r-tp2,b-st,r,j-la,r--" +
	"r-p,b-bl,u-n,u-sp-d,r-s-h-h,u,j-d,r-b,v--b-b,v-b-b-r--r,j-p-d-d,u-u,v-k,u-r-n,u-k,u-h,u-k,u-h,u,j-la,u,v--" +
	"r-r-n,u-r,j-d,b,v-d,u,v-s,b-s,u-k,r-d,u,j-r-p,u-h,r,j-h,b-h,r-k,u-u,j--u,v,rs-d,b-d,u-b-r-p--bl,r-n,u-k,u-b,bs-b-u--" +
	"r-ua-u,j-b-p,b-p,u-k,b-k,b-k,u-b,bs-r-s-h-s,u-h,u,bs-s,r-k,u-u-b---rtp,u-u,v---u-bl-sp-d,b-d,u,j-r--" +
	"r-da-u,j--u,j--p-u-n-n,r-p,u,v-s,b-h,r,rs-h,r-h,b-h,u,v-p-rtp,r-r-p,b,v-r-k,r-b-b-p,u-k,r-d,b-p,u-r-k,u-u,v--" +
	"r-r-k,r-u-k,u-b,bs-u,bs-k,u-ext,n-n-n,r-k,r-h,u-h,u,v-k,u-h-s-s,u-b,v-u,rs-u-k,b-k,b-k,b-k-k,b-k,u-b,v-b-b-u,v--" +
	"r-tp1,u-k-k,u--b-bl,u,bs-n,u-bl,n,b-n-n,u,v-k,u-h,r,j-h,u-s,b-h,b-h,u,v-b-u,v,j---ra-bl,u-n,u-k,u-b-u-bl,n,b,v-n-n,b-n,r--" +
	"r-k,b-k,u-r,rs-r-traps-st--u,j-n,u,bs-u-s,b-h,u,j-h-h,u-k,u-h,u,bs-b-st,r,j-b,v-b-u,v-k,u-bl,u,bs-tp1,b-b--u,j-n,u-k,r-n,u,v--" +
	"r-r,j-b-r-r-b,bs-b-traps,u-r-b,bs-b--r-h,u,j-h-p,u,j-h,r-k,u-b--r--r,rs-ua,b,bs,r,rs-ra,b-ra,u,j-u,v-k,b-k,b-k,u-r--" +
	"r--r-p,b,v,r,j-u--u,j-b-r,rs-r-k,u-p,b-u,bs-h,r-h,u,bs-h,r,rs-h,b-s,u-k,r-b-u,v-da-da,r-b--r----traps-r--" +
	"r-b-b-u,j-b-u-k,b-k,u-u-b-u,j-la,b-la,b-st,u-h,b-h,u-k,b-k,b-k,b-k,u-b-b-b-u-st,b-u,j-b-traps,b-b-b-st,u-";